
!UNDEF NO_BINPLACE
!UNDEF NTDBGFILES

BUILD_NO_SYMCHK=1
BINPLACE_PLACEFILE=..\..\placefil.txt
!IF "$(NETDISK_BINPLACE_TYPE)" == "exe"
_NTTREE=..\..\exe\$(BUILD_ALT_DIR)
!ELSE 
#default "$(NETDISK_BINPLACE_TYPE)" == "sys"
_NTTREE=..\..\sys\$(BUILD_ALT_DIR)
!ENDIF

# C:\DEVELOP\NETDISK\TRUNK\LANSCSISYSTEMV2

!INCLUDE "oem.inc"
