#pragma once

#define DBG_LEVEL_NDAS_STATUS	2
#define DBG_LEVEL_NDAS_DEV		1
#define DBG_LEVEL_NDAS_OP		2

#define DBG_LEVEL_COMM			2
#define DBG_LEVEL_COMM_DEV		2

#define DBG_LEVEL_LPX_TRANS		2

#define DBG_LEVEL_NB_MAIN		2

#define DBG_LEVEL_NDAS_MAGM		2
#define DBG_LEVEL_MAGM_MAIN		2
#define DBG_LEVEL_MAGM_PAGE		1
#define DBG_LEVEL_MAGM_DLG		1
#define DBG_LEVEL_MAGM_EVENT	2
#define DBG_LEVEL_MAGM_REG_WIZ	2
#define DBG_LEVEL_MAGM_OPTION	2
#define DBG_LEVEL_MAGM_CLS		2
#define DBG_LEVEL_MAGM_TASK		2
#define DBG_LEVEL_MAGM_ABOUT	2

#define DBG_LEVEL_SVC_MAIN		2
#define DBG_LEVEL_NDAS_SVC		2
#define DBG_LEVEL_SVC_REG		2
#define DBG_LEVEL_SVC_COM_PROC	2
#define DBG_LEVEL_SVC_LOGDEV	2
#define DBG_LEVEL_SVC_DEV		2
#define DBG_LEVEL_SVC_PNP		2
#define DBG_LEVEL_SVC_UNIT		2
#define DBG_LEVEL_SVC_HB		2
#define DBG_LEVEL_SVC_AUTO_REG	2
#define DBG_LEVEL_SVC_EVENT		2
#define DBG_LEVEL_SVC_UNIT_FACT	2
#define DBG_LEVEL_SVC_HIXC		2
#define DBG_LEVEL_SVC_HIXS		2
#define DBG_LEVEL_SVC_IX		2

#define DBG_LEVEL_VOL_CMD		1
#define DBG_LEVEL_VOL_DEV		1
#define DBG_LEVEL_VOL			1
#define DBG_LEVEL_VOL_DEV		1
