#ifndef _NDAS_TYPE_STR_H_
#define _NDAS_TYPE_STR_H_

#ifndef _NDAS_TYPE_H_
#error This header requires ndastype.h to be included false
#endif

#pragma once

//////////////////////////////////////////////////////////////////////////

#define BEGIN_ENUM_STRING(x) switch(x) {
#define ENUM_STRING(x) case x: {return TEXT(#x);}
#define ENUM_STRING2(x,y) case x: {return TEXT(y);}
#define ENUM_STRING_DEFAULT(x) default: {return TEXT(x);}
#define END_ENUM_STRING() }

//////////////////////////////////////////////////////////////////////////

__inline LPCTSTR NdasUnitDeviceTypeString(NDAS_UNITDEVICE_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_UNITDEVICE_TYPE_UNKNOWN, "UNKNOWN")
		ENUM_STRING2(NDAS_UNITDEVICE_TYPE_DISK, "DISK")
		ENUM_STRING2(NDAS_UNITDEVICE_TYPE_COMPACT_BLOCK, "COMPACT_BLOCK")
		ENUM_STRING2(NDAS_UNITDEVICE_TYPE_CDROM, "CDROM")
		ENUM_STRING2(NDAS_UNITDEVICE_TYPE_OPTICAL_MEMORY, "OPTICAL_MEM")
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_TYPE_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasUnitDeviceDiskTypeString(NDAS_UNITDEVICE_DISK_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_UNITDEVICE_DISK_TYPE_UNKNOWN, "UNKNOWN")
		ENUM_STRING2(NDAS_UNITDEVICE_DISK_TYPE_SINGLE, "SINGLE")
		ENUM_STRING2(NDAS_UNITDEVICE_DISK_TYPE_CONFLICT, "CONFLICT")		
		ENUM_STRING2(NDAS_UNITDEVICE_DISK_TYPE_AGGREGATED, "AGGREGATED")
		ENUM_STRING2(NDAS_UNITDEVICE_DISK_TYPE_MIRROR_MASTER, "MIRRORED(M)")
		ENUM_STRING2(NDAS_UNITDEVICE_DISK_TYPE_MIRROR_SLAVE, "MIRRORED(S)")
		ENUM_STRING2(NDAS_UNITDEVICE_DISK_TYPE_RAID0, "RAID0")
		ENUM_STRING2(NDAS_UNITDEVICE_DISK_TYPE_RAID1, "RAID1")
		ENUM_STRING2(NDAS_UNITDEVICE_DISK_TYPE_RAID4, "RAID4")
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_DISK_TYPE_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasUnitDeviceCDROMTypeString(NDAS_UNITDEVICE_CDROM_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_UNITDEVICE_CDROM_TYPE_UNKNOWN, "UNKNOWN")
		ENUM_STRING2(NDAS_UNITDEVICE_CDROM_TYPE_CD, "CD")
		ENUM_STRING2(NDAS_UNITDEVICE_CDROM_TYPE_DVD, "DVD")
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_CDROM_TYPE_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasDeviceStatusString(NDAS_DEVICE_STATUS x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_DEVICE_STATUS_UNKNOWN, "UNKNOWN")
		ENUM_STRING2(NDAS_DEVICE_STATUS_NOT_REGISTERED, "DISABLED")
		ENUM_STRING2(NDAS_DEVICE_STATUS_OFFLINE, "DISCONNECTED")
		ENUM_STRING2(NDAS_DEVICE_STATUS_CONNECTING, "CONNECTING")
		ENUM_STRING2(NDAS_DEVICE_STATUS_ONLINE, "CONNECTED")
		ENUM_STRING_DEFAULT("NDAS_DEVICE_STATUS_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasDeviceErrorString(NDAS_DEVICE_ERROR x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_DEVICE_ERROR_NONE, "NONE")
		ENUM_STRING2(NDAS_DEVICE_ERROR_UNSUPPORTED_VERSION, "UNSUPPORTED VERSION")
		ENUM_STRING2(NDAS_DEVICE_ERROR_LPX_SOCKET_FAILED, "LPX FAILURE")
		ENUM_STRING2(NDAS_DEVICE_ERROR_DISCOVER_FAILED, "DISCOVER FAILURE")
		ENUM_STRING2(NDAS_DEVICE_ERROR_LOGIN_FAILED, "LOGIN FAILURE")
		ENUM_STRING2(NDAS_DEVICE_ERROR_FROM_SYSTEM, "SYSTEM FAILURE")
		ENUM_STRING_DEFAULT("NDAS_DEVICE_ERROR_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasUnitDeviceStatusString(NDAS_UNITDEVICE_STATUS x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_UNITDEVICE_STATUS_UNKNOWN, "UNKNOWN")
		ENUM_STRING2(NDAS_UNITDEVICE_STATUS_NOT_MOUNTED, "NOT MOUNTED")
		ENUM_STRING2(NDAS_UNITDEVICE_STATUS_MOUNTED, "MOUNTED")
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_STATUS_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasUnitDeviceErrorString(NDAS_UNITDEVICE_ERROR x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_UNITDEVICE_ERROR_NONE, "NONE")
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_ERROR_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasLogicalDeviceStatusString(NDAS_LOGICALDEVICE_STATUS x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_LOGICALDEVICE_STATUS_UNKNOWN, "UNKNOWN")
		ENUM_STRING2(NDAS_LOGICALDEVICE_STATUS_UNMOUNTED, "UNMOUNTED")
		ENUM_STRING2(NDAS_LOGICALDEVICE_STATUS_MOUNT_PENDING, "MOUNT_PENDING")
		ENUM_STRING2(NDAS_LOGICALDEVICE_STATUS_MOUNTED, "MOUNTED")
		ENUM_STRING2(NDAS_LOGICALDEVICE_STATUS_UNMOUNT_PENDING, "UNMOUNT_PENDING")
		ENUM_STRING2(NDAS_LOGICALDEVICE_STATUS_NOT_INITIALIZED, "NOT_INITIALIZED")
//		ENUM_STRING2(NDAS_LOGICALDEVICE_STATUS_NOT_MOUNTABLE, "NOT_MOUNTABLE")
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_STATUS_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasLogicalDeviceErrorString(NDAS_LOGICALDEVICE_ERROR x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_LOGICALDEVICE_ERROR_NONE, "NONE")
		/* ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_FROM_DRIVER) */
		ENUM_STRING2(NDAS_LOGICALDEVICE_ERROR_MISSING_MEMBER, "MISSING MEMBER")
		ENUM_STRING2(NDAS_LOGICALDEVICE_ERROR_REQUIRE_UPGRADE, "REQUIRE MIGRATION")
		ENUM_STRING2(NDAS_LOGICALDEVICE_ERROR_REQUIRE_RESOLUTION, "REQUIRE BINDTOOL")
		/* ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_INVALID_MEMBER) */
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_ERROR_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasLogicalDeviceTypeString(NDAS_LOGICALDEVICE_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_DISK_SINGLE, "SINGLE")
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_DISK_MIRRORED, "MIRRORED")
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_DISK_AGGREGATED, "AGGREGATED")
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_DISK_RAID0, "RAID0")
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_DISK_RAID1, "RAID1")
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_DISK_RAID4, "RAID4")
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_DVD, "DVD")
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_VIRTUAL_DVD, "VDVD")
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_MO, "MO")
		ENUM_STRING2(NDAS_LOGICALDEVICE_TYPE_FLASHCARD, "FLASHCARD")
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_TYPE_???")
	END_ENUM_STRING()
}

//////////////////////////////////////////////////////////////////////////

#undef BEGIN_ENUM_STRING
#undef ENUM_STRING
#undef ENUM_STRING_DEFAULT
#undef END_ENUM_STRING

//////////////////////////////////////////////////////////////////////////

#endif /* _NDAS_TYPE_STR_H_ */
