#pragma once

#include <pshpack1.h>

#define NHIX_HIC_OS_UNKNOWN		0x00
#define NHIX_HIC_OS_WIN9X		0x01
#define NHIX_HIC_OS_WINNT		0x02
#define NHIX_HIC_OS_LINUX		0x03
#define NHIX_HIC_OS_WINCE		0x04
#define NHIX_HIC_OS_PS2			0x05
#define NHIX_HIC_OS_MAC			0x06
#define NHIX_HIC_OS_EMBEDDED_OS	0x07
#define NHIX_HIC_OS_OTHER		0xFF

typedef UCHAR NDAS_HOST_OS_TYPE;

typedef struct _NDAS_HOST_INFO_VERINFO {
	WORD VersionMajor;
	WORD VersionMinor;
	WORD VersionBuild;
	WORD VersionPrivate;
} NDAS_HOST_INFO_VERINFO, *PNDAS_HOST_INFO_VERINFO;

typedef struct _NDAS_HOST_INFO_LPX_ADDR {
	BYTE Bytes[6];
} NDAS_HOST_INFO_LPX_ADDR, *PNDAS_HOST_INFO_LPX_ADDR;

typedef struct _NDAS_HOST_INFO_LPX_ADDR_ARRAY {
	UCHAR AddressCount;
	NDAS_HOST_INFO_LPX_ADDR Addresses[4];
} NDAS_HOST_INFO_LPX_ADDR_ARRAY, *PNDAS_HOST_INFO_LPX_ADDR_ARRAY;

typedef struct _NDAS_HOST_INFO_IPV4_ADDR {
	BYTE Bytes[4];
} NDAS_HOST_INFO_IPV4_ADDR, *PNDAS_HOST_INFO_IPV4_ADDR;

typedef struct _NDAS_HOST_INFO_IPV4_ADDR_ARRAY {
	UCHAR AddressCount;
	NDAS_HOST_INFO_IPV4_ADDR Addresses[4];
} NDAS_HOST_INFO_IPV4_ADDR_ARRAY, *PNDAS_HOST_INFO_IPV4_ADDR_ARRAY;

typedef struct _NDAS_HOST_INFO_IPV6_ADDR {
	BYTE Bytes[16];
} NDAS_HOST_INFO_IPV6_ADDR, *PNDAS_HOST_INFO_IPV6_ADDR;

typedef struct _NDAS_HOST_INFO_IPV6_ADDR_ARRAY {
	UCHAR AddressCount;
	NDAS_HOST_INFO_IPV6_ADDR Addresses[2];
} NDAS_HOST_INFO_IPV6_ADDR_ARRAY, *PNDAS_HOST_INFO_IPV6_ADDR_ARRAY;

typedef struct _NDAS_HOST_INFO {
	NDAS_HOST_OS_TYPE OSType;
	WCHAR szHostname[48];
	WCHAR szFQDN[48];
	NDAS_HOST_INFO_VERINFO OSVerInfo;
	NDAS_HOST_INFO_VERINFO ReservedVerInfo;
	NDAS_HOST_INFO_VERINFO NDASSWVerInfo;
	NDAS_HOST_INFO_LPX_ADDR_ARRAY LPXAddrs;
	NDAS_HOST_INFO_IPV4_ADDR_ARRAY IPV4Addrs;
	NDAS_HOST_INFO_IPV6_ADDR_ARRAY IPV6Addrs;
	UCHAR TransportFlags;
	ULONG FeatureFlags;
} NDAS_HOST_INFOW, *PNDAS_HOST_INFOW;

typedef CONST NDAS_HOST_INFOW* PCNDAS_HOST_INFOW;

typedef struct _NDAS_HOST_INFOA {
	NDAS_HOST_OS_TYPE OSType;
	CHAR szHostname[48];
	CHAR szFQDN[48];
	NDAS_HOST_INFO_VERINFO OSVerInfo;
	NDAS_HOST_INFO_VERINFO ReservedVerInfo;
	NDAS_HOST_INFO_VERINFO NDASSWVerInfo;
	NDAS_HOST_INFO_LPX_ADDR_ARRAY LPXAddrs;
	NDAS_HOST_INFO_IPV4_ADDR_ARRAY IPV4Addrs;
	NDAS_HOST_INFO_IPV6_ADDR_ARRAY IPV6Addrs;
	UCHAR TransportFlags;
	ULONG FeatureFlags;
} NDAS_HOST_INFOA, *PNDAS_HOST_INFOA;

typedef CONST NDAS_HOST_INFOA* PCNDAS_HOST_INFOA;

#ifdef UNICODE
#define NDAS_HOST_INFO NDAS_HOST_INFOW
#define PNDAS_HOST_INFO PNDAS_HOST_INFOW
#define PCNDAS_HOST_INFO PCNDAS_HOST_INFOW
#else
#define NDAS_HOST_INFO NDAS_HOST_INFOA
#define PNDAS_HOST_INFO PNDAS_HOST_INFOA
#define PCNDAS_HOST_INFO PCNDAS_HOST_INFOA
#endif

#include <poppack.h>
