
PRECOMPILED_INCLUDE=port.h
PRECOMPILED_PCH=portpch.pch
PRECOMPILED_OBJ=portpch.obj

SOURCES=control.c  \
        dispatch.c \
        enable.c   \
        enum.c     \
        init.c     \
        internal.c \
        lock.c     \
        map.c      \
        pdo.c      \
        pnp.c      \
        pnpstop.c  \
        port.c     \
        power.c    \
        prop.c     \
        remove.c   \
        utils.c    \
        wmi.c      \


