/////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2004-2005 XIMETA, Inc.
// All rights reserved.
//
// Module Name:
//
//    ndasmsg.h
//
// Abstract:
//
//    NDAS Error Messages and Event Log Messages
//
//Notes:
//
//	   DO NOT EDIT THIS FILE BY HAND!
//
//    This file is GENERATED from the 'ndasmsg.xml'.
//
//////////////////////////////////////////////////////////////////////////


#ifndef __NDASMSG_H_
#define __NDASMSG_H_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: NDAS_ERROR_INVALID_ID_FORMAT
//
// MessageText:
//
//  NDAS device ID or Key is invalid.
//
#define NDAS_ERROR_INVALID_ID_FORMAT     ((DWORD)0xE00F0001L)

//
// MessageId: NDASSVC_ERROR_DEVICE_ENTRY_NOT_FOUND
//
// MessageText:
//
//  NDAS Device Entry Not Found.
//
#define NDASSVC_ERROR_DEVICE_ENTRY_NOT_FOUND ((DWORD)0xE0100021L)

//
// MessageId: NDASSVC_ERROR_UNITDEVICE_ENTRY_NOT_FOUND
//
// MessageText:
//
//  NDAS Unit Device Entry Not Found.
//
#define NDASSVC_ERROR_UNITDEVICE_ENTRY_NOT_FOUND ((DWORD)0xE0100022L)

//
// MessageId: NDASSVC_ERROR_LOGICALDEVICE_ENTRY_NOT_FOUND
//
// MessageText:
//
//  NDAS Logical Device Entry Not Found.
//
#define NDASSVC_ERROR_LOGICALDEVICE_ENTRY_NOT_FOUND ((DWORD)0xE0100023L)

//
// MessageId: NDASSVC_ERROR_CANNOT_DISABLE_MOUNTED_DEVICE
//
// MessageText:
//
//  Disabling the NDAS device containing any of the mounted unit device is not allowed.
//
#define NDASSVC_ERROR_CANNOT_DISABLE_MOUNTED_DEVICE ((DWORD)0xE0100024L)

//
// MessageId: NDASSVC_ERROR_CANNOT_UNREGISTER_ENABLED_DEVICE
//
// MessageText:
//
//  Unregistering an enabled NDAS device is not permitted.
//
#define NDASSVC_ERROR_CANNOT_UNREGISTER_ENABLED_DEVICE ((DWORD)0xE0100031L)

//
// MessageId: NDASSVC_ERROR_INVALID_SLOT_NUMBER
//
// MessageText:
//
//  Invalid NDAS slot number.
//
#define NDASSVC_ERROR_INVALID_SLOT_NUMBER ((DWORD)0xE0100032L)

//
// MessageId: NDASSVC_ERROR_SLOT_ALREADY_OCCUPIED
//
// MessageText:
//
//  Requested slot is used by another device.
//
#define NDASSVC_ERROR_SLOT_ALREADY_OCCUPIED ((DWORD)0xE0100033L)

//
// MessageId: NDASSVC_ERROR_DUPLICATE_DEVICE_ENTRY
//
// MessageText:
//
//  The requested NDAS device already exists.
//
#define NDASSVC_ERROR_DUPLICATE_DEVICE_ENTRY ((DWORD)0xE0100034L)

//
// MessageId: NDASSVC_ERROR_DEVICE_ENTRY_SLOT_FULL
//
// MessageText:
//
//  No more NDAS device slot is available.
//
#define NDASSVC_ERROR_DEVICE_ENTRY_SLOT_FULL ((DWORD)0xE0100035L)

//
// MessageId: NDASSVC_ERROR_NDAS_LOGICALDEVICE_NOT_INITIALIZED
//
// MessageText:
//
//  NDAS Logical device is not initialized.
//
#define NDASSVC_ERROR_NDAS_LOGICALDEVICE_NOT_INITIALIZED ((DWORD)0xE0100041L)

//
// MessageId: NDASSVC_ERROR_NDAS_LOGICALDEVICE_MEMBER_MISSING
//
// MessageText:
//
//  Some NDAS logical device members are missing in the entry.
//
#define NDASSVC_ERROR_NDAS_LOGICALDEVICE_MEMBER_MISSING ((DWORD)0xE0100042L)

//
// MessageId: NDASSVC_ERROR_NDAS_LOGICALDEVICE_NOT_MOUNTED
//
// MessageText:
//
//  NDAS Logical device is not mounted.
//
#define NDASSVC_ERROR_NDAS_LOGICALDEVICE_NOT_MOUNTED ((DWORD)0xE0100043L)

//
// MessageId: NDASSVC_ERROR_CONFLICT_LOGICALDEVICE_ENTRY
//
// MessageText:
//
//  NDAS Logical device entry is conflicts with existing entries.
//
#define NDASSVC_ERROR_CONFLICT_LOGICALDEVICE_ENTRY ((DWORD)0xE0100044L)

//
// MessageId: NDASSVC_ERROR_DUPLICATE_LOGICALDEVICE_ENTRY
//
// MessageText:
//
//  The requested NDAS logical device already exists.
//
#define NDASSVC_ERROR_DUPLICATE_LOGICALDEVICE_ENTRY ((DWORD)0xE0100045L)

//
// MessageId: NDASSVC_ERROR_LOGICALDEVICE_SLOT_FULL
//
// MessageText:
//
//  No more NDAS logical device slot is available.
//
#define NDASSVC_ERROR_LOGICALDEVICE_SLOT_FULL ((DWORD)0xE0100046L)

//
// MessageId: NDASSVC_ERROR_UNSUPPORTED_LOGICALDEVICE_TYPE
//
// MessageText:
//
//  Unsupported NDAS logical device type.
//
#define NDASSVC_ERROR_UNSUPPORTED_LOGICALDEVICE_TYPE ((DWORD)0xE0100047L)

//
// MessageId: NDASSVC_ERROR_NDAS_LOGICALDEVICE_INVALID_BIND_INFORMATION
//
// MessageText:
//
//  The bind information in NDAS device is invalid.
//
#define NDASSVC_ERROR_NDAS_LOGICALDEVICE_INVALID_BIND_INFORMATION ((DWORD)0xE0100048L)

//
// MessageId: NDASSVC_ERROR_NDAS_LOGICALDEVICE_MODIFIED_BIND_INFORMATION
//
// MessageText:
//
//  The bind information in NDAS device is changed.
//
#define NDASSVC_ERROR_NDAS_LOGICALDEVICE_MODIFIED_BIND_INFORMATION ((DWORD)0xE0100049L)

//
// MessageId: NDASSVC_ERROR_NDAS_LOGICALDEVICE_ACCESS_DENIED
//
// MessageText:
//
//  Granted access for the NDAS logical device is insufficent to complete the operation.
//
#define NDASSVC_ERROR_NDAS_LOGICALDEVICE_ACCESS_DENIED ((DWORD)0xE0100050L)

//
// MessageId: NDASSVC_ERROR_NDAS_LOGICALDEVICE_ACCESS_FAILED
//
// MessageText:
//
//  Requested access to the NDAS logical device is failed.
//
#define NDASSVC_ERROR_NDAS_LOGICALDEVICE_ACCESS_FAILED ((DWORD)0xE0100051L)

//
// MessageId: NDASSVC_ERROR_NDAS_LOGICALDEVICE_NOT_UNMOUNTED
//
// MessageText:
//
//  NDAS logical device is not in a mountable status.
//
#define NDASSVC_ERROR_NDAS_LOGICALDEVICE_NOT_UNMOUNTED ((DWORD)0xE0100052L)

//
// MessageId: NDASSVC_ERROR_NDAS_UNITDEVICE_NOT_MOUNTED
//
// MessageText:
//
//  NDAS Unit device is not mounted.
//
#define NDASSVC_ERROR_NDAS_UNITDEVICE_NOT_MOUNTED ((DWORD)0xE0100053L)

//
// MessageId: NDASSVC_ERROR_NDAS_HOST_INFO_NOT_FOUND
//
// MessageText:
//
//  NDAS Host Information cannot be found.
//
#define NDASSVC_ERROR_NDAS_HOST_INFO_NOT_FOUND ((DWORD)0xE0100061L)

//
// MessageId: NDASSVC_ERROR_NDAS_DEVICE_COMMUNICATION_FAILURE
//
// MessageText:
//
//  Communication to the NDAS Device has failed.
//
#define NDASSVC_ERROR_NDAS_DEVICE_COMMUNICATION_FAILURE ((DWORD)0xE0100062L)

//
// MessageId: NDASSVC_ERROR_MULTIPLE_WRITE_ACCESS_NOT_ALLOWED
//
// MessageText:
//
//  Multiple Write Access is not allowed for the specified NDAS unit device.
//
#define NDASSVC_ERROR_MULTIPLE_WRITE_ACCESS_NOT_ALLOWED ((DWORD)0xE0100063L)

//
// MessageId: NDASSVC_ERROR_INCOMPATIBLE_HOSTS_FOR_MULTIPLE_WRITE_ACCESS
//
// MessageText:
//
//  Incompatible NDAS hosts for multiple write-access are found for the specified NDAS unit device.
//
#define NDASSVC_ERROR_INCOMPATIBLE_HOSTS_FOR_MULTIPLE_WRITE_ACCESS ((DWORD)0xE0100064L)

//
// MessageId: NDASSVC_ERROR_NO_MORE_DVD_WRITE_ACCESS_INSTANCE_ALLOWED
//
// MessageText:
//
//  No more than constrained instances of DVD Drives as Read/Write mode is allowed.
//
#define NDASSVC_ERROR_NO_MORE_DVD_WRITE_ACCESS_INSTANCE_ALLOWED ((DWORD)0xE0100065L)

//
// MessageId: NDASSVC_ERROR_NDAS_LOGICALDEVICE_CORRUPTED_BIND_INFORMATION
//
// MessageText:
//
//  The NDAS device is corrupted and need to be recovered before mounting.
//
#define NDASSVC_ERROR_NDAS_LOGICALDEVICE_CORRUPTED_BIND_INFORMATION ((DWORD)0xE0100066L)

//
// MessageId: NDASSVC_ERROR_COMMAND_VERSION_NOT_SUPPORTED
//
// MessageText:
//
//  Command version is unsupported.
//
#define NDASSVC_ERROR_COMMAND_VERSION_NOT_SUPPORTED ((DWORD)0xE01000E0L)

//
// MessageId: NDASSVC_ERROR_NOT_IMPLEMENTED
//
// MessageText:
//
//  Requested feature is not supported.
//
#define NDASSVC_ERROR_NOT_IMPLEMENTED    ((DWORD)0xE01000E1L)

//
// MessageId: NDASSVC_ERROR_ROFILTER_VERSION_MISMATCH
//
// MessageText:
//
//  Unsupported Read-only filter version.
//
#define NDASSVC_ERROR_ROFILTER_VERSION_MISMATCH ((DWORD)0xE01000C0L)

//
// MessageId: NDASSVC_ERROR_INVALID_SERVICE_PARAMETER
//
// MessageText:
//
//  Invalid service parameter.
//
#define NDASSVC_ERROR_INVALID_SERVICE_PARAMETER ((DWORD)0xE01000D0L)

//
// MessageId: NDASUSER_ERROR_SERVICE_CONNECTION_FAILURE
//
// MessageText:
//
//  Communication to the NDAS service failed.
//
#define NDASUSER_ERROR_SERVICE_CONNECTION_FAILURE ((DWORD)0xE0010001L)

//
// MessageId: NDASUSER_ERROR_INVALID_DEVICE_STRING_ID_OR_KEY
//
// MessageText:
//
//  NDAS Device ID or Key is invalid.
//
#define NDASUSER_ERROR_INVALID_DEVICE_STRING_ID_OR_KEY ((DWORD)0xE0010002L)

//
// MessageId: NDASUSER_ERROR_INVALID_DEVICE_STRING_ID
//
// MessageText:
//
//  NDAS Device ID is invalid.
//
#define NDASUSER_ERROR_INVALID_DEVICE_STRING_ID ((DWORD)0xE0010003L)

//
// MessageId: NDASUSER_ERROR_INVALID_DEVICE_STRING_KEY
//
// MessageText:
//
//  NDAS Device Key is invalid.
//
#define NDASUSER_ERROR_INVALID_DEVICE_STRING_KEY ((DWORD)0xE0010004L)

//
// MessageId: NDASUSER_ERROR_INVALID_PARAMETER
//
// MessageText:
//
//  Invalid parameter.
//
#define NDASUSER_ERROR_INVALID_PARAMETER ((DWORD)0xE00100FFL)

//
// MessageId: NDASUSER_ERROR_NDAS_LOGICALDEVICE_ACCESS_DENIED
//
// MessageText:
//
//  NDAS Logical device access denied.
//
#define NDASUSER_ERROR_NDAS_LOGICALDEVICE_ACCESS_DENIED ((DWORD)0xE0010050L)

//
// MessageId: NDASUSER_ERROR_SERVICE_RETURNED_NOT_IMPLEMENTED
//
// MessageText:
//
//  NDAS Service does not support the requested operation.
//
#define NDASUSER_ERROR_SERVICE_RETURNED_NOT_IMPLEMENTED ((DWORD)0xE0010101L)

//
// MessageId: NDASUSER_ERROR_SERVICE_RETURNED_INVALID_REQUEST
//
// MessageText:
//
//  Operation is invalid to the NDAS service.
//
#define NDASUSER_ERROR_SERVICE_RETURNED_INVALID_REQUEST ((DWORD)0xE0010102L)

//
// MessageId: NDASUSER_ERROR_SERVICE_RETURNED_TERMINATION
//
// MessageText:
//
//  NDAS Service is terminating.
//
#define NDASUSER_ERROR_SERVICE_RETURNED_TERMINATION ((DWORD)0xE0010103L)

//
// MessageId: NDASUSER_ERROR_SERVICE_RETURNED_UNSUPPORTED_VERSION
//
// MessageText:
//
//  Unsupported NDAS service version.
//
#define NDASUSER_ERROR_SERVICE_RETURNED_UNSUPPORTED_VERSION ((DWORD)0xE0010104L)

//
// MessageId: NDASUSER_ERROR_EVENT_VERSION_MISMATCH
//
// MessageText:
//
//  Unsupport NDAS service event version.
//
#define NDASUSER_ERROR_EVENT_VERSION_MISMATCH ((DWORD)0xE0010200L)

//
// MessageId: NDASUSER_ERROR_EVENT_CALLBACK_FULL
//
// MessageText:
//
//  No more NDAS event callback is available.
//
#define NDASUSER_ERROR_EVENT_CALLBACK_FULL ((DWORD)0xE0010201L)

//
// MessageId: NDASUSER_ERROR_INVALID_EVENT_CALLBACK_HANDLE
//
// MessageText:
//
//  Invalid NDAS event callback handle.
//
#define NDASUSER_ERROR_INVALID_EVENT_CALLBACK_HANDLE ((DWORD)0xE0010202L)

//
// MessageId: NDASUSER_ERROR_NOT_IMPLEMENTED
//
// MessageText:
//
//  Requested feature is not supported.
//
#define NDASUSER_ERROR_NOT_IMPLEMENTED   ((DWORD)0xE00100E1L)

//
// MessageId: NDASCOMM_ERROR_INTERNAL
//
// MessageText:
//
//  Internal error.
//
#define NDASCOMM_ERROR_INTERNAL          ((DWORD)0xE0020000L)

//
// MessageId: NDASCOMM_ERROR_NOT_IMPLEMENTED
//
// MessageText:
//
//  Requested feature is not supported.
//
#define NDASCOMM_ERROR_NOT_IMPLEMENTED   ((DWORD)0xE0020001L)

//
// MessageId: NDASCOMM_ERROR_INVALID_PARAMETER
//
// MessageText:
//
//  Invalid parameter.
//
#define NDASCOMM_ERROR_INVALID_PARAMETER ((DWORD)0xE0020002L)

//
// MessageId: NDASCOMM_WARNING_CONNECTION_FAIL
//
// MessageText:
//
//  Connection failed to the NDAS device.
//
#define NDASCOMM_WARNING_CONNECTION_FAIL ((DWORD)0xA0020003L)

//
// MessageId: NDASCOMM_ERROR_LOGIN_COMMUNICATION
//
// MessageText:
//
//  Communication error during login process.
//
#define NDASCOMM_ERROR_LOGIN_COMMUNICATION ((DWORD)0xE0020004L)

//
// MessageId: NDASCOMM_ERROR_RI_NOT_EXIST
//
// MessageText:
//
//  Internal error : NDASCOMM_ERROR_RI_NOT_EXIST.
//
#define NDASCOMM_ERROR_RI_NOT_EXIST      ((DWORD)0xE0020005L)

//
// MessageId: NDASCOMM_ERROR_RI_BAD_COMMAND
//
// MessageText:
//
//  Internal error : NDASCOMM_ERROR_RI_BAD_COMMAND.
//
#define NDASCOMM_ERROR_RI_BAD_COMMAND    ((DWORD)0xE0020006L)

//
// MessageId: NDASCOMM_ERROR_RI_COMMAND_FAILED
//
// MessageText:
//
//  Internal error : NDASCOMM_ERROR_RI_COMMAND_FAILED.
//
#define NDASCOMM_ERROR_RI_COMMAND_FAILED ((DWORD)0xE0020007L)

//
// MessageId: NDASCOMM_ERROR_HARDWARE_UNSUPPORTED
//
// MessageText:
//
//  Internal error : NDASCOMM_ERROR_HARDWARE_UNSUPPORTED.
//
#define NDASCOMM_ERROR_HARDWARE_UNSUPPORTED ((DWORD)0xE0020008L)

//
// MessageId: NDASCOMM_ERROR_T_NOT_EXIST
//
// MessageText:
//
//  Internal error : NDASCOMM_ERROR_T_NOT_EXIST.
//
#define NDASCOMM_ERROR_T_NOT_EXIST       ((DWORD)0xE0020009L)

//
// MessageId: NDASCOMM_ERROR_T_BAD_COMMAND
//
// MessageText:
//
//  Internal error : NDASCOMM_ERROR_T_BAD_COMMAND.
//
#define NDASCOMM_ERROR_T_BAD_COMMAND     ((DWORD)0xE002000AL)

//
// MessageId: NDASCOMM_ERROR_T_COMMAND_FAILED
//
// MessageText:
//
//  Internal error : NDASCOMM_ERROR_T_COMMAND_FAILED.
//
#define NDASCOMM_ERROR_T_COMMAND_FAILED  ((DWORD)0xE002000BL)

//
// MessageId: NDASCOMM_ERROR_T_BROKEN_DATA
//
// MessageText:
//
//  Internal error : NDASCOMM_ERROR_T_BROKEN_DATA.
//
#define NDASCOMM_ERROR_T_BROKEN_DATA     ((DWORD)0xE002000CL)

//
// MessageId: NDASCOMM_ERROR_RI_AUTH_FAILED
//
// MessageText:
//
//  Internal error : NDASCOMM_ERROR_RI_AUTH_FAILED.
//
#define NDASCOMM_ERROR_RI_AUTH_FAILED    ((DWORD)0xE002000DL)

//
// MessageId: NDASCOMM_ERROR_LOGIN_UNKNOWN
//
// MessageText:
//
//  Unknown error for login process.
//
#define NDASCOMM_ERROR_LOGIN_UNKNOWN     ((DWORD)0xE002000EL)

//
// MessageId: NDASCOMM_ERROR_RW_USER_EXIST
//
// MessageText:
//
//  The NDAS device is being used by another process(es) or host(s) with read-write access privilege.
//
#define NDASCOMM_ERROR_RW_USER_EXIST     ((DWORD)0xE002000FL)

//
// MessageId: NDASCOMM_ERROR_NOT_ENOUGH_MEMORY
//
// MessageText:
//
//  Not enough memory to complete job.
//
#define NDASCOMM_ERROR_NOT_ENOUGH_MEMORY ((DWORD)0xE0020010L)

//
// MessageId: NDASCOMM_ERROR_PROTOCOL
//
// MessageText:
//
//  Lanscsi protocol error.
//
#define NDASCOMM_ERROR_PROTOCOL          ((DWORD)0xE0020011L)

//
// MessageId: NDASCOMM_ERROR_INVALID_OPERATION
//
// MessageText:
//
//  Invalid operation.
//
#define NDASCOMM_ERROR_INVALID_OPERATION ((DWORD)0xE002FFFFL)

//
// MessageId: NDASOP_ERROR_NOT_IMPLEMENTED
//
// MessageText:
//
//  Requested feature is not supported.
//
#define NDASOP_ERROR_NOT_IMPLEMENTED     ((DWORD)0xE0030001L)

//
// MessageId: NDASOP_ERROR_DEVICE_FAIL
//
// MessageText:
//
//  Accessing to the device is failed.
//
#define NDASOP_ERROR_DEVICE_FAIL         ((DWORD)0xE0030002L)

//
// MessageId: NDASOP_ERROR_NOT_SINGLE_DISK
//
// MessageText:
//
//  The NDAS device must be a single disk to operate this job.
//
#define NDASOP_ERROR_NOT_SINGLE_DISK     ((DWORD)0xE0030003L)

//
// MessageId: NDASOP_ERROR_DEVICE_UNSUPPORTED
//
// MessageText:
//
//  The NDAS device is not supported. If the device is HDD device, convert the device to a single disk before doing this job.
//
#define NDASOP_ERROR_DEVICE_UNSUPPORTED  ((DWORD)0xE0030004L)

//
// MessageId: NDASOP_ERROR_NOT_BOUND_DISK
//
// MessageText:
//
//  The NDAS device must be a bound disk to operate this job.
//
#define NDASOP_ERROR_NOT_BOUND_DISK      ((DWORD)0xE0030005L)

//
// MessageId: NDASOP_ERROR_INVALID_PARAMETER
//
// MessageText:
//
//  Invalid parameter.
//
#define NDASOP_ERROR_INVALID_PARAMETER   ((DWORD)0xE0030006L)

//
// MessageId: NDASOP_ERROR_NOT_ENOUGH_MEMORY
//
// MessageText:
//
//  Not enough memory to complete job.
//
#define NDASOP_ERROR_NOT_ENOUGH_MEMORY   ((DWORD)0xE0030007L)

//
// MessageId: NDASOP_ERROR_INVALID_DISK_COUNT
//
// MessageText:
//
//  Incorrect disk count to bind disks.
//
#define NDASOP_ERROR_INVALID_DISK_COUNT  ((DWORD)0xE0030008L)

//
// MessageId: NDASOP_ERROR_ALREADY_USED
//
// MessageText:
//
//  The NDAS device is being used by another process(es) or host(s).
//
#define NDASOP_ERROR_ALREADY_USED        ((DWORD)0xE0030009L)

//
// MessageId: NDASOP_ERROR_INVALID_BIND_MIGRATE
//
// MessageText:
//
//  The NDAS device has invalid bind information to migrate.
//
#define NDASOP_ERROR_INVALID_BIND_MIGRATE ((DWORD)0xE003000AL)

//
// MessageId: NDASOP_ERROR_BIND_SIZE_LIMIT
//
// MessageText:
//
//  The total size of the bound disks cannot exceed 2TB. This limitation is imposed by Windows OS.
//
#define NDASOP_ERROR_BIND_SIZE_LIMIT     ((DWORD)0xE003000BL)

//
// MessageId: NDASOP_ERROR_TOO_MANY_MISSING_MEMBER
//
// MessageText:
//
//  There is too many missing member to replace(repair) in bound disks.
//
#define NDASOP_ERROR_TOO_MANY_MISSING_MEMBER ((DWORD)0xE003000CL)

//
// MessageId: NDASOP_ERROR_NO_MISSING_MEMBER
//
// MessageText:
//
//  There is no missing NDAS device to replace(repair) in bound disks.
//
#define NDASOP_ERROR_NO_MISSING_MEMBER   ((DWORD)0xE003000DL)

//
// MessageId: NDASOP_ERROR_CRITICAL_REPAIR
//
// MessageText:
//
//  There was a critial error while replaceing(repairing) bound disks.
//
#define NDASOP_ERROR_CRITICAL_REPAIR     ((DWORD)0xE003000EL)

//
// MessageId: NDASOP_ERROR_REPLACE_TOO_SMALL
//
// MessageText:
//
//  Size of a replacement disk is too small.
//
#define NDASOP_ERROR_REPLACE_TOO_SMALL   ((DWORD)0xE003000FL)

//
// MessageId: NDASOP_ERROR_BIND_UNSUPPORTED
//
// MessageText:
//
//  This type of RAID does not support the requested command.
//
#define NDASOP_ERROR_BIND_UNSUPPORTED    ((DWORD)0xE0030010L)

//
// MessageId: NDASOP_ERROR_NOT_ENOUGH_CAPACITY
//
// MessageText:
//
//  The device does not have enough capacity to operate request command.
//
#define NDASOP_ERROR_NOT_ENOUGH_CAPACITY ((DWORD)0xE0030011L)

//
// MessageId: NDASVOL_ERROR_NON_NDAS_VOLUME
//
// MessageText:
//
//  The specified volume is not related with the NDAS devices.
//
#define NDASVOL_ERROR_NON_NDAS_VOLUME    ((DWORD)0xE0050001L)

//
// MessageId: NDASPATCH_ERROR_NOT_IMPLEMENTED
//
// MessageText:
//
//  Requested feature is not supported.
//
#define NDASPATCH_ERROR_NOT_IMPLEMENTED  ((DWORD)0xE00400B1L)

//
// MessageId: NDASDM_ERROR_NON_SCSI_TYPE_DEVICE
//
// MessageText:
//
//  Non-SCSI type device is found.
//
#define NDASDM_ERROR_NON_SCSI_TYPE_DEVICE ((DWORD)0xE1100100L)

//
// MessageId: NDASDM_ERROR_SRB_IO_CONTROL_ERROR
//
// MessageText:
//
//  SRB IO CONTROL Error
//
#define NDASDM_ERROR_SRB_IO_CONTROL_ERROR ((DWORD)0xE1100102L)

//
// MessageId: EVT_NDASSVC_ERROR_GET_SYS_KEY
//
// MessageText:
//
//  The NDAS disk is encrypted and the corresponding NDAS system key is not registered in the system.
//
#define EVT_NDASSVC_ERROR_GET_SYS_KEY    ((DWORD)0xEF000101L)

//
// MessageId: EVT_NDASSVC_ERROR_SYS_KEY_MISMATCH
//
// MessageText:
//
//  NDAS system key does not match with the NDAS disk key.
//
#define EVT_NDASSVC_ERROR_SYS_KEY_MISMATCH ((DWORD)0xEF000102L)

//
// MessageId: EVT_NDASSVC_ERROR_CEB_CRC_MISMATCH
//
// MessageText:
//
//  Invalid CEB CRC.
//
#define EVT_NDASSVC_ERROR_CEB_CRC_MISMATCH ((DWORD)0xEF000103L)

//
// MessageId: EVT_NDASSVC_ERROR_CEB_UNSUPPORTED_REVISION
//
// MessageText:
//
//  Unsupported CEB Revision.
//
#define EVT_NDASSVC_ERROR_CEB_UNSUPPORTED_REVISION ((DWORD)0xEF000104L)

//
// MessageId: EVT_NDASSVC_ERROR_CEB_INVALID_KEY_LENGTH
//
// MessageText:
//
//  CEB Key Length is invalid.
//
#define EVT_NDASSVC_ERROR_CEB_INVALID_KEY_LENGTH ((DWORD)0xEF000105L)

//
// MessageId: EVT_NDASSVC_ERROR_CEB_READ_FAILURE
//
// MessageText:
//
//  Failed to read CEB.
//
#define EVT_NDASSVC_ERROR_CEB_READ_FAILURE ((DWORD)0xEF000106L)

//
// MessageId: EVT_NDASSVC_ERROR_KEY_GENERATION_FAILURE
//
// MessageText:
//
//  CE key generation failed.
//
#define EVT_NDASSVC_ERROR_KEY_GENERATION_FAILURE ((DWORD)0xEF000107L)

//
// MessageId: EVT_NDASSVC_INFO_AUTOREG_NDAS_DEVICE_FOUND
//
// MessageText:
//
//  A new NDAS Device is found from the network and is being registered.
//
#define EVT_NDASSVC_INFO_AUTOREG_NDAS_DEVICE_FOUND ((DWORD)0x6F000108L)

//
// MessageId: EVT_NDASSVC_INFO_NDASDEV_UNKNOWN_VERSION_FMT2
//
// MessageText:
//
//  Unsupported hardware version (%2) detected from the NDAS Device (%1).
//
#define EVT_NDASSVC_INFO_NDASDEV_UNKNOWN_VERSION_FMT2 ((DWORD)0x6F000109L)

//
// MessageId: NDAS_CR_DEFAULT
//
// MessageText:
//
//  CR_DEFAULT
//
#define NDAS_CR_DEFAULT                  ((DWORD)0xE1F00001L)

//
// MessageId: NDAS_CR_OUT_OF_MEMORY
//
// MessageText:
//
//  CR_OUT_OF_MEMORY
//
#define NDAS_CR_OUT_OF_MEMORY            ((DWORD)0xE1F00002L)

//
// MessageId: NDAS_CR_INVALID_POINTER
//
// MessageText:
//
//  CR_INVALID_POINTER
//
#define NDAS_CR_INVALID_POINTER          ((DWORD)0xE1F00003L)

//
// MessageId: NDAS_CR_INVALID_FLAG
//
// MessageText:
//
//  CR_INVALID_FLAG
//
#define NDAS_CR_INVALID_FLAG             ((DWORD)0xE1F00004L)

//
// MessageId: NDAS_CR_INVALID_DEVINST
//
// MessageText:
//
//  CR_INVALID_DEVINST
//
#define NDAS_CR_INVALID_DEVINST          ((DWORD)0xE1F00005L)

//
// MessageId: NDAS_CR_INVALID_RES_DES
//
// MessageText:
//
//  CR_INVALID_RES_DES
//
#define NDAS_CR_INVALID_RES_DES          ((DWORD)0xE1F00006L)

//
// MessageId: NDAS_CR_INVALID_LOG_CONF
//
// MessageText:
//
//  CR_INVALID_LOG_CONF
//
#define NDAS_CR_INVALID_LOG_CONF         ((DWORD)0xE1F00007L)

//
// MessageId: NDAS_CR_INVALID_ARBITRATOR
//
// MessageText:
//
//  CR_INVALID_ARBITRATOR
//
#define NDAS_CR_INVALID_ARBITRATOR       ((DWORD)0xE1F00008L)

//
// MessageId: NDAS_CR_INVALID_NODELIST
//
// MessageText:
//
//  CR_INVALID_NODELIST
//
#define NDAS_CR_INVALID_NODELIST         ((DWORD)0xE1F00009L)

//
// MessageId: NDAS_CR_DEVINST_HAS_REQS
//
// MessageText:
//
//  CR_DEVINST_HAS_REQS
//
#define NDAS_CR_DEVINST_HAS_REQS         ((DWORD)0xE1F0000AL)

//
// MessageId: NDAS_CR_INVALID_RESOURCEID
//
// MessageText:
//
//  CR_INVALID_RESOURCEID
//
#define NDAS_CR_INVALID_RESOURCEID       ((DWORD)0xE1F0000BL)

//
// MessageId: NDAS_CR_DLVXD_NOT_FOUND
//
// MessageText:
//
//  CR_DLVXD_NOT_FOUND
//
#define NDAS_CR_DLVXD_NOT_FOUND          ((DWORD)0xE1F0000CL)

//
// MessageId: NDAS_CR_NO_SUCH_DEVINST
//
// MessageText:
//
//  CR_NO_SUCH_DEVINST
//
#define NDAS_CR_NO_SUCH_DEVINST          ((DWORD)0xE1F0000DL)

//
// MessageId: NDAS_CR_NO_MORE_LOG_CONF
//
// MessageText:
//
//  CR_NO_MORE_LOG_CONF
//
#define NDAS_CR_NO_MORE_LOG_CONF         ((DWORD)0xE1F0000EL)

//
// MessageId: NDAS_CR_NO_MORE_RES_DES
//
// MessageText:
//
//  CR_NO_MORE_RES_DES
//
#define NDAS_CR_NO_MORE_RES_DES          ((DWORD)0xE1F0000FL)

//
// MessageId: NDAS_CR_ALREADY_SUCH_DEVINST
//
// MessageText:
//
//  CR_ALREADY_SUCH_DEVINST
//
#define NDAS_CR_ALREADY_SUCH_DEVINST     ((DWORD)0xE1F00010L)

//
// MessageId: NDAS_CR_INVALID_RANGE_LIST
//
// MessageText:
//
//  CR_INVALID_RANGE_LIST
//
#define NDAS_CR_INVALID_RANGE_LIST       ((DWORD)0xE1F00011L)

//
// MessageId: NDAS_CR_INVALID_RANGE
//
// MessageText:
//
//  CR_INVALID_RANGE
//
#define NDAS_CR_INVALID_RANGE            ((DWORD)0xE1F00012L)

//
// MessageId: NDAS_CR_FAILURE
//
// MessageText:
//
//  CR_FAILURE
//
#define NDAS_CR_FAILURE                  ((DWORD)0xE1F00013L)

//
// MessageId: NDAS_CR_NO_SUCH_LOGICAL_DEV
//
// MessageText:
//
//  CR_NO_SUCH_LOGICAL_DEV
//
#define NDAS_CR_NO_SUCH_LOGICAL_DEV      ((DWORD)0xE1F00014L)

//
// MessageId: NDAS_CR_CREATE_BLOCKED
//
// MessageText:
//
//  CR_CREATE_BLOCKED
//
#define NDAS_CR_CREATE_BLOCKED           ((DWORD)0xE1F00015L)

//
// MessageId: NDAS_CR_NOT_SYSTEM_VM
//
// MessageText:
//
//  CR_NOT_SYSTEM_VM
//
#define NDAS_CR_NOT_SYSTEM_VM            ((DWORD)0xE1F00016L)

//
// MessageId: NDAS_CR_REMOVE_VETOED
//
// MessageText:
//
//  CR_REMOVE_VETOED
//
#define NDAS_CR_REMOVE_VETOED            ((DWORD)0xE1F00017L)

//
// MessageId: NDAS_CR_APM_VETOED
//
// MessageText:
//
//  CR_APM_VETOED
//
#define NDAS_CR_APM_VETOED               ((DWORD)0xE1F00018L)

//
// MessageId: NDAS_CR_INVALID_LOAD_TYPE
//
// MessageText:
//
//  CR_INVALID_LOAD_TYPE
//
#define NDAS_CR_INVALID_LOAD_TYPE        ((DWORD)0xE1F00019L)

//
// MessageId: NDAS_CR_BUFFER_SMALL
//
// MessageText:
//
//  CR_BUFFER_SMALL
//
#define NDAS_CR_BUFFER_SMALL             ((DWORD)0xE1F0001AL)

//
// MessageId: NDAS_CR_NO_ARBITRATOR
//
// MessageText:
//
//  CR_NO_ARBITRATOR
//
#define NDAS_CR_NO_ARBITRATOR            ((DWORD)0xE1F0001BL)

//
// MessageId: NDAS_CR_NO_REGISTRY_HANDLE
//
// MessageText:
//
//  CR_NO_REGISTRY_HANDLE
//
#define NDAS_CR_NO_REGISTRY_HANDLE       ((DWORD)0xE1F0001CL)

//
// MessageId: NDAS_CR_REGISTRY_ERROR
//
// MessageText:
//
//  CR_REGISTRY_ERROR
//
#define NDAS_CR_REGISTRY_ERROR           ((DWORD)0xE1F0001DL)

//
// MessageId: NDAS_CR_INVALID_DEVICE_ID
//
// MessageText:
//
//  CR_INVALID_DEVICE_ID
//
#define NDAS_CR_INVALID_DEVICE_ID        ((DWORD)0xE1F0001EL)

//
// MessageId: NDAS_CR_INVALID_DATA
//
// MessageText:
//
//  CR_INVALID_DATA
//
#define NDAS_CR_INVALID_DATA             ((DWORD)0xE1F0001FL)

//
// MessageId: NDAS_CR_INVALID_API
//
// MessageText:
//
//  CR_INVALID_API
//
#define NDAS_CR_INVALID_API              ((DWORD)0xE1F00020L)

//
// MessageId: NDAS_CR_DEVLOADER_NOT_READY
//
// MessageText:
//
//  CR_DEVLOADER_NOT_READY
//
#define NDAS_CR_DEVLOADER_NOT_READY      ((DWORD)0xE1F00021L)

//
// MessageId: NDAS_CR_NEED_RESTART
//
// MessageText:
//
//  CR_NEED_RESTART
//
#define NDAS_CR_NEED_RESTART             ((DWORD)0xE1F00022L)

//
// MessageId: NDAS_CR_NO_MORE_HW_PROFILES
//
// MessageText:
//
//  CR_NO_MORE_HW_PROFILES
//
#define NDAS_CR_NO_MORE_HW_PROFILES      ((DWORD)0xE1F00023L)

//
// MessageId: NDAS_CR_DEVICE_NOT_THERE
//
// MessageText:
//
//  CR_DEVICE_NOT_THERE
//
#define NDAS_CR_DEVICE_NOT_THERE         ((DWORD)0xE1F00024L)

//
// MessageId: NDAS_CR_NO_SUCH_VALUE
//
// MessageText:
//
//  CR_NO_SUCH_VALUE
//
#define NDAS_CR_NO_SUCH_VALUE            ((DWORD)0xE1F00025L)

//
// MessageId: NDAS_CR_WRONG_TYPE
//
// MessageText:
//
//  CR_WRONG_TYPE
//
#define NDAS_CR_WRONG_TYPE               ((DWORD)0xE1F00026L)

//
// MessageId: NDAS_CR_INVALID_PRIORITY
//
// MessageText:
//
//  CR_INVALID_PRIORITY
//
#define NDAS_CR_INVALID_PRIORITY         ((DWORD)0xE1F00027L)

//
// MessageId: NDAS_CR_NOT_DISABLEABLE
//
// MessageText:
//
//  CR_NOT_DISABLEABLE
//
#define NDAS_CR_NOT_DISABLEABLE          ((DWORD)0xE1F00028L)

//
// MessageId: NDAS_CR_FREE_RESOURCES
//
// MessageText:
//
//  CR_FREE_RESOURCES
//
#define NDAS_CR_FREE_RESOURCES           ((DWORD)0xE1F00029L)

//
// MessageId: NDAS_CR_QUERY_VETOED
//
// MessageText:
//
//  CR_QUERY_VETOED
//
#define NDAS_CR_QUERY_VETOED             ((DWORD)0xE1F0002AL)

//
// MessageId: NDAS_CR_CANT_SHARE_IRQ
//
// MessageText:
//
//  CR_CANT_SHARE_IRQ
//
#define NDAS_CR_CANT_SHARE_IRQ           ((DWORD)0xE1F0002BL)

//
// MessageId: NDAS_CR_NO_DEPENDENT
//
// MessageText:
//
//  CR_NO_DEPENDENT
//
#define NDAS_CR_NO_DEPENDENT             ((DWORD)0xE1F0002CL)

//
// MessageId: NDAS_CR_SAME_RESOURCES
//
// MessageText:
//
//  CR_SAME_RESOURCES
//
#define NDAS_CR_SAME_RESOURCES           ((DWORD)0xE1F0002DL)

//
// MessageId: NDAS_CR_NO_SUCH_REGISTRY_KEY
//
// MessageText:
//
//  CR_NO_SUCH_REGISTRY_KEY
//
#define NDAS_CR_NO_SUCH_REGISTRY_KEY     ((DWORD)0xE1F0002EL)

//
// MessageId: NDAS_CR_INVALID_MACHINENAME
//
// MessageText:
//
//  CR_INVALID_MACHINENAME
//
#define NDAS_CR_INVALID_MACHINENAME      ((DWORD)0xE1F0002FL)

//
// MessageId: NDAS_CR_REMOTE_COMM_FAILURE
//
// MessageText:
//
//  CR_REMOTE_COMM_FAILURE
//
#define NDAS_CR_REMOTE_COMM_FAILURE      ((DWORD)0xE1F00030L)

//
// MessageId: NDAS_CR_MACHINE_UNAVAILABLE
//
// MessageText:
//
//  CR_MACHINE_UNAVAILABLE
//
#define NDAS_CR_MACHINE_UNAVAILABLE      ((DWORD)0xE1F00031L)

//
// MessageId: NDAS_CR_NO_CM_SERVICES
//
// MessageText:
//
//  CR_NO_CM_SERVICES
//
#define NDAS_CR_NO_CM_SERVICES           ((DWORD)0xE1F00032L)

//
// MessageId: NDAS_CR_ACCESS_DENIED
//
// MessageText:
//
//  CR_ACCESS_DENIED
//
#define NDAS_CR_ACCESS_DENIED            ((DWORD)0xE1F00033L)

//
// MessageId: NDAS_CR_CALL_NOT_IMPLEMENTED
//
// MessageText:
//
//  CR_CALL_NOT_IMPLEMENTED
//
#define NDAS_CR_CALL_NOT_IMPLEMENTED     ((DWORD)0xE1F00034L)

//
// MessageId: NDAS_CR_INVALID_PROPERTY
//
// MessageText:
//
//  CR_INVALID_PROPERTY
//
#define NDAS_CR_INVALID_PROPERTY         ((DWORD)0xE1F00035L)

//
// MessageId: NDAS_CR_DEVICE_INTERFACE_ACTIVE
//
// MessageText:
//
//  CR_DEVICE_INTERFACE_ACTIVE
//
#define NDAS_CR_DEVICE_INTERFACE_ACTIVE  ((DWORD)0xE1F00036L)

//
// MessageId: NDAS_CR_NO_SUCH_DEVICE_INTERFACE
//
// MessageText:
//
//  CR_NO_SUCH_DEVICE_INTERFACE
//
#define NDAS_CR_NO_SUCH_DEVICE_INTERFACE ((DWORD)0xE1F00037L)

//
// MessageId: NDAS_CR_INVALID_REFERENCE_STRING
//
// MessageText:
//
//  CR_INVALID_REFERENCE_STRING
//
#define NDAS_CR_INVALID_REFERENCE_STRING ((DWORD)0xE1F00038L)

//
// MessageId: NDAS_CR_INVALID_CONFLICT_LIST
//
// MessageText:
//
//  CR_INVALID_CONFLICT_LIST
//
#define NDAS_CR_INVALID_CONFLICT_LIST    ((DWORD)0xE1F00039L)

//
// MessageId: NDAS_CR_INVALID_INDEX
//
// MessageText:
//
//  CR_INVALID_INDEX
//
#define NDAS_CR_INVALID_INDEX            ((DWORD)0xE1F0003AL)

//
// MessageId: NDAS_CR_INVALID_STRUCTURE_SIZE
//
// MessageText:
//
//  CR_INVALID_STRUCTURE_SIZE
//
#define NDAS_CR_INVALID_STRUCTURE_SIZE   ((DWORD)0xE1F0003BL)

//
// MessageId: NDAS_CR_CODE_3C
//
// MessageText:
//
//  CR_CODE_3C
//
#define NDAS_CR_CODE_3C                  ((DWORD)0xE1F0003CL)

//
// MessageId: NDAS_CR_CODE_3D
//
// MessageText:
//
//  CR_CODE_3D
//
#define NDAS_CR_CODE_3D                  ((DWORD)0xE1F0003DL)

//
// MessageId: NDAS_CR_CODE_3E
//
// MessageText:
//
//  CR_CODE_3E
//
#define NDAS_CR_CODE_3E                  ((DWORD)0xE1F0003EL)

//
// MessageId: NDAS_CR_CODE_3F
//
// MessageText:
//
//  CR_CODE_3F
//
#define NDAS_CR_CODE_3F                  ((DWORD)0xE1F0003FL)

#endif /* __NDASMSG_H_ */
