#ifndef _NETKINGCALL_MIB_H_
#define _NETKINGCALL_MIB_H_

//
// SNMP port Number.
//
#define SNMP_PORT_NUMBER		9000	// 161
#define SNMP_TRAP_PORT_NUMBER	9001	//162
#define	COMMUNITY				"public"
#define	DEFAULT_IP				"0.0.0.0" //"127.0.0.1"
#define	AGENT_IP				"127.0.0.1"

//
//	LanscsiHelper-extended SNMP error code
//
// SNMP Error Codes Returned in Error_status Field of PDU
// (these are NOT WinSNMP API Error Codes)
// See WinSnmp.h
//
#define LSHSNMP_ERROR_CODE_BASE						( 0x1000 )
#define LSHSNMP_ERROR_NOT_COMPATIBLE_PRIMARY		( LSHSNMP_ERROR_CODE_BASE + 0 )
#define LSHSNMP_ERROR_NO_NETDISK					( LSHSNMP_ERROR_CODE_BASE + 1 )
#define LSHSNMP_ERROR_SUSPECTED_HANG				( LSHSNMP_ERROR_CODE_BASE + 2 )
#define LSHSNMP_ERROR_ALREADY_ENABLED				( LSHSNMP_ERROR_CODE_BASE + 3 )
#define LSHSNMP_ERROR_LAST							( LSHSNMP_ERROR_CODE_BASE + 3 )


//
// MIB Variable access privileges.
//
#define MIB_ACCESS_READ			0
#define MIB_ACCESS_WRITE		1
#define MIB_ACCESS_READWRITE	2

//
// Enum for RowStatus
//
#define MIB_ROWSTATUS_ACTIVE		1
#define MIB_ROWSTATUS_NOTINSERVICE	2
#define MIB_ROWSTATUS_NOTREADY		3
#define MIB_ROWSTATUS_CREATEANDGO	4
#define MIB_ROWSTATUS_CREATEANDWAIT	5
#define	MIB_ROWSTATUS_DESTROY		6

//
// OID...
//

#define NETKINGCALL_OID						"1.3.6.1.4.1.15163"

#define	NETDISK_NUMBER_OID					".2.1.0"

// LanDisk Table.
#define	NDT_ROW_STATUS_OID					".2.2.1.1"
#define	NDT_ADDRESS_OID						".2.2.1.2"
#define	NDT_NAME_OID						".2.2.1.3"
#define NDT_SERIAL_OID						".2.2.1.4"
#define	NDT_STATUS_OID						".2.2.1.5"
#define NDT_SLOT_NUMBER_OID					".2.2.1.6"
#define	NDT_FIRST_UNITDISK_STATUS_OID		".2.2.1.7"
#define	NDT_FIRST_UNITDISK_SIZE_OID			".2.2.1.8"
#define	NDT_FIRST_UNITDISK_SETTING_OID		".2.2.1.9"
#define NDT_FIRST_UNITDISK_RW_HOST_OID		".2.2.1.10"
#define NDT_FIRST_UNITDISK_RO_HOST_OID		".2.2.1.11"
#define	NDT_SECOND_UNITDISK_STATUS_OID		".2.2.1.12"
#define	NDT_SECOND_UNITDISK_SIZE_OID		".2.2.1.13"
#define	NDT_SECOND_UNITDISK_SETTING_OID		".2.2.1.14"
#define NDT_SECOND_UNITDISK_RW_HOST_OID		".2.2.1.15"
#define NDT_SECOND_UNITDISK_RO_HOST_OID		".2.2.1.16"
#define	NDT_THIRD_UNITDISK_STATUS_OID		".2.2.1.17"
#define	NDT_THIRD_UNITDISK_SIZE_OID			".2.2.1.18"
#define	NDT_THIRD_UNITDISK_SETTING_OID		".2.2.1.19"
#define NDT_THIRD_UNITDISK_RW_HOST_OID		".2.2.1.20"
#define NDT_THIRD_UNITDISK_RO_HOST_OID		".2.2.1.21"
#define	NDT_FOURTH_UNITDISK_STATUS_OID		".2.2.1.22"
#define	NDT_FOURTH_UNITDISK_SIZE_OID		".2.2.1.23"
#define	NDT_FOURTH_UNITDISK_SETTING_OID		".2.2.1.24"
#define NDT_FOURTH_UNITDISK_RW_HOST_OID		".2.2.1.25"
#define NDT_FOURTH_UNITDISK_RO_HOST_OID		".2.2.1.26"

#define	NETDISK_REFRESH_OID					".2.3.0"

#define NDT_XTH_UNITDISK_OID				".2.2.1"
#define NDT_FIRST_UNITDISK_STATUS_NUMBER	7
#define NDT_FIRST_UNITDISK_SETTING_NUMBER	9

#define NDT_NUMBER_OF_TABLE_ENTRYS			26

#define UNITDISK_STATUS_OID_TO_UNITDISK_NUMBER(_LAST_OID_)	\
		((_LAST_OID_ - NDT_FIRST_UNITDISK_STATUS_NUMBER) / 5)

#define UNITDISK_SETTING_OID_TO_UNITDISK_NUMBER(_LAST_OID_)	\
		((_LAST_OID_ - NDT_FIRST_UNITDISK_SETTING_NUMBER) / 5)

#define UNITDISK_NUMBER_TO_UNITDISK_STATUS_OID(_UNIT_NUMBER_)	\
		(NDT_FIRST_UNITDISK_STATUS_NUMBER + (_UNIT_NUMBER_ * 5))

#define UNITDISK_NUMBER_TO_UNITDISK_SETTING_OID(_UNIT_NUMBER_)	\
		(NDT_FIRST_UNITDISK_SETTING_NUMBER + (_UNIT_NUMBER_ * 5))

//
// Mirror storage format.
//
#define _MIB_UNITDISK_SETTING_FORMAT	\
	UCHAR		m_ucAccessRight;		\
	UCHAR		m_ucDiskType;			\
	UCHAR		m_ucPeerAddress[6];		\
	UCHAR		m_ucPeerUnitNumber;		\
	UCHAR		m_ucDiskUsageType;

typedef struct _MIB_UNITDISK_SETTING {
	_MIB_UNITDISK_SETTING_FORMAT
} MIB_UNITDISK_SETTING, *PMIB_UNITDISK_SETTING;
		
#endif