#pragma once

#include "ndastype.h"

#define BEGIN_ENUM_STRING(x) switch(x) {
#define ENUM_STRING(x) case x: {return TEXT(#x);}
#define ENUM_STRING_DEFAULT(x) default: {return TEXT(x);}
#define END_ENUM_STRING() }

inline LPCTSTR NdasCmdTypeString(NDAS_CMD_TYPE cmd)
{
	BEGIN_ENUM_STRING(cmd)
		ENUM_STRING(NDAS_CMD_TYPE_NONE)
		ENUM_STRING(NDAS_CMD_TYPE_REGISTER_DEVICE)
		ENUM_STRING(NDAS_CMD_TYPE_UNREGISTER_DEVICE)
		ENUM_STRING(NDAS_CMD_TYPE_ENUMERATE_DEVICES)
		ENUM_STRING(NDAS_CMD_TYPE_SET_DEVICE_PARAM)
		ENUM_STRING(NDAS_CMD_TYPE_QUERY_DEVICE_STATUS)
		ENUM_STRING(NDAS_CMD_TYPE_QUERY_DEVICE_INFORMATION)
		ENUM_STRING(NDAS_CMD_TYPE_ENUMERATE_UNITDEVICES)
		ENUM_STRING(NDAS_CMD_TYPE_SET_UNITDEVICE_PARAM)
		ENUM_STRING(NDAS_CMD_TYPE_QUERY_UNITDEVICE_STATUS)
		ENUM_STRING(NDAS_CMD_TYPE_QUERY_UNITDEVICE_INFORMATION)
		ENUM_STRING(NDAS_CMD_TYPE_FIND_LOGICALDEVICE_OF_UNITDEVICE)
		ENUM_STRING(NDAS_CMD_TYPE_ENUMERATE_LOGICALDEVICES)
		ENUM_STRING(NDAS_CMD_TYPE_SET_LOGICALDEVICE_PARAM)
		ENUM_STRING(NDAS_CMD_TYPE_QUERY_LOGICALDEVICE_STATUS)
		ENUM_STRING(NDAS_CMD_TYPE_QUERY_LOGICALDEVICE_INFORMATION)
		ENUM_STRING(NDAS_CMD_TYPE_PLUGIN_LOGICALDEVICE)
		ENUM_STRING(NDAS_CMD_TYPE_EJECT_LOGICALDEVICE)
		ENUM_STRING(NDAS_CMD_TYPE_UNPLUG_LOGICALDEVICE)
		ENUM_STRING_DEFAULT("NDAS_CMD_TYPE_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasCmdStatusString(NDAS_CMD_STATUS status)
{
	BEGIN_ENUM_STRING(status)
		ENUM_STRING(NDAS_CMD_STATUS_REQUEST)
		ENUM_STRING(NDAS_CMD_STATUS_SUCCESS)
		ENUM_STRING(NDAS_CMD_STATUS_FAILED)
		ENUM_STRING(NDAS_CMD_STATUS_ERROR_NOT_IMPLEMENTED)
		ENUM_STRING(NDAS_CMD_STATUS_INVALID_REQUEST)
		ENUM_STRING(NDAS_CMD_STATUS_TERMINATION)
		ENUM_STRING(NDAS_CMD_STATUS_UNSUPPORTED_VERSION)
		ENUM_STRING_DEFAULT("NDAS_CMD_STATUS_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasUnitDeviceTypeString(NDAS_UNITDEVICE_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_UNITDEVICE_TYPE_UNKNOWN)
		ENUM_STRING(NDAS_UNITDEVICE_TYPE_DISK)
		ENUM_STRING(NDAS_UNITDEVICE_TYPE_CD)
		ENUM_STRING(NDAS_UNITDEVICE_TYPE_DVD)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_TYPE_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasUnitDeviceDiskTypeString(NDAS_DISK_UNIT_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_UNKNOWN)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_SINGLE)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_CONFLICT)		
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_AGGREGATION_MASTER)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_AGGREGATION_SLAVE)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_MIRROR_MASTER)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_MIRROR_SLAVE)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_DISK_TYPE_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasUnitDeviceDvdTypeString(NDAS_UNITDEVICE_DVD_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_UNITDEVICE_DVD_TYPE_UNKNOWN)
		ENUM_STRING(NDAS_UNITDEVICE_DVD_TYPE_DVDROM)
		ENUM_STRING(NDAS_UNITDEVICE_DVD_TYPE_DVDRWPLUS)
		ENUM_STRING(NDAS_UNITDEVICE_DVD_TYPE_DVDRWMINUS)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_DVD_TYPE_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasDeviceStatusString(NDAS_DEVICE_STATUS x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_DEVICE_STATUS_UNKNOWN)
		ENUM_STRING(NDAS_DEVICE_STATUS_NOT_REGISTERED)
		ENUM_STRING(NDAS_DEVICE_STATUS_OFFLINE)
		ENUM_STRING(NDAS_DEVICE_STATUS_ONLINE)
		ENUM_STRING_DEFAULT("NDAS_DEVICE_STATUS_???")
	END_ENUM_STRING()
}


inline LPCTSTR NdasDeviceErrorString(NDAS_DEVICE_ERROR x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_DEVICE_ERROR_NONE)
		ENUM_STRING(NDAS_DEVICE_ERROR_UNSUPPORTED_VERSION)
		ENUM_STRING(NDAS_DEVICE_ERROR_LPX_SOCKET_FAILED)
		ENUM_STRING(NDAS_DEVICE_ERROR_DISCOVER_FAILED)
		ENUM_STRING(NDAS_DEVICE_ERROR_LOGIN_FAILED)
		ENUM_STRING(NDAS_DEVICE_ERROR_FROM_SYSTEM)
		ENUM_STRING_DEFAULT("NDAS_DEVICE_ERROR_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasUnitDeviceErrorString(NDAS_UNITDEVICE_ERROR x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_DEVICE_ERROR_FROM_SYSTEM)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_ERROR_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasUnitDeviceStatusString(NDAS_UNITDEVICE_STATUS x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_UNITDEVICE_STATUS_UNKNOWN)
		ENUM_STRING(NDAS_UNITDEVICE_STATUS_NOT_MOUNTED)
		ENUM_STRING(NDAS_UNITDEVICE_STATUS_MOUNTED)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_STATUS_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasLogicalDeviceStatusString(NDAS_LOGICALDEVICE_STATUS x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_UNKNOWN)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_NOT_MOUNTED)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_MOUNT_PENDING)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_MOUNTED)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_UNMOUNT_PENDING)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_NOT_INITIALIZED)
//		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_NOT_MOUNTABLE)
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_STATUS_???")
	END_ENUM_STRING()
}

#define NDAS_UNITDEVICE_ERROR_NONE	0x0000


inline LPCTSTR NdasLogicalDeviceErrorString(NDAS_LOGICALDEVICE_ERROR x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_NONE)
		/* ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_FROM_DRIVER) */
		ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_MISSING_MEMBER)
		/* ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_INVALID_MEMBER) */
		ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_REQUIRE_UPGRADE)
		ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_REQUIRE_RESOLUTION)
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_ERROR_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasLogicalDeviceTypeString(NDAS_LOGICALDEVICE_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_DISK)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_DVDROM)
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_TYPE_???")
	END_ENUM_STRING()
}

inline LPCTSTR NdasLogicalDeviceDiskTypeString(NDAS_LOGICALDEVICE_DISK_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_LOGICALDEVICE_DISK_TYPE_SINGLE)
		ENUM_STRING(NDAS_LOGICALDEVICE_DISK_TYPE_MIRRORED)
		ENUM_STRING(NDAS_LOGICALDEVICE_DISK_TYPE_AGGREGATED)
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_DISK_TYPE_???")
	END_ENUM_STRING()
}

#undef BEGIN_ENUM_STRING
#undef ENUM_STRING
#undef ENUM_STRING_DEFAULT
#undef END_ENUM_STRING
