//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by xtaskdialog.rc
//
#define IDI_XTASKDIALOG_COMMANDLINK     901
#define IDI_XTASKDIALOG_SHIELD          902
#define IDI_XTASKDIALOG_HOT_COMMANDLINK 903
#define IDI_XTASKDIALOG_ERROR           904
#define IDI_XTASKDIALOG_WARNING         905
#define IDI_XTASKDIALOG_INFORMATION     906
#define IDS_XTASKDIALOG_BUTTON_CAPTION0 12100
#define IDS_XTASKDIALOG_BUTTON_CAPTION1 12101
#define IDS_XTASKDIALOG_BUTTON_CAPTION2 12102
#define IDS_XTASKDIALOG_BUTTON_CAPTION3 12103
#define IDS_XTASKDIALOG_BUTTON_CAPTION4 12104
#define IDS_XTASKDIALOG_BUTTON_CAPTION5 12105
#define IDS_XTASKDIALOG_SHOW_DETAILS 12106
#define IDS_XTASKDIALOG_HIDE_DETAILS 12107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
