#pragma once

#define IDI_UPDATE					   99
#define IDC_DOWNLOAD_ICON             101
#define IDC_DOWNLOAD_CANCEL           102
#define IDC_DOWNLOAD_BANNER           103
#define IDC_DOWNLOAD_PROGRESSBAR      104
#define IDC_DOWNLOAD_ACTIONTEXT       105

#define IDS_UPDATER_TITLE	900

#define IDS_CANCEL	1000
#define IDS_OK		1001
#define IDS_YES		1002
#define IDS_NO		1003
#define IDS_CLOSE	1004

#define IDS_UPDATER_ERROR_FMT	1010
#define IDS_UPDATER_ERROR_UPDATE_CHECK	1011
#define IDS_UPDATER_ERROR_DOWNLOAD		1012

#define IDS_STATUS_CHECK_UPDATE			1101
#define IDS_STATUS_CHECK_UPDATE_DONE	1102
#define	IDS_STATUS_DOWNLOAD_UPDATE		1103
#define IDS_STATUS_DOWNLOAD_UPDATE_DONE	1104
#define	IDS_NO_UPDATE	1051
#define	IDS_NEW_UPDATE	1052

#define IDD_PROGRESS                 1101
