// 8DDAA062-1E63-4DE9-8AB7-89C7EA33E3CF 
#define NDASSVC_WPP_CONTROL_GUIDS \
	WPP_DEFINE_CONTROL_GUID(NdasServiceTraceGuid,(8DDAA062,1E63,4DE9,8AB7,89C7EA33E3CF), \
		WPP_DEFINE_BIT(NDASSVC_GENERAL) \
		WPP_DEFINE_BIT(NDASSVC_INIT) \
		WPP_DEFINE_BIT(NDASSVC_PNP) \
		WPP_DEFINE_BIT(NDASSVC_HIXSERVER) \
		WPP_DEFINE_BIT(NDASSVC_HIXCLIENT) \
		WPP_DEFINE_BIT(NDASSVC_CMDSERVER) \
		WPP_DEFINE_BIT(NDASSVC_CMDPROCESSOR) \
		WPP_DEFINE_BIT(NDASSVC_NDASDEVICEREGISTRAR) \
		WPP_DEFINE_BIT(NDASSVC_NDASLOGDEVMANAGER) \
		WPP_DEFINE_BIT(NDASSVC_NDASDEVICE) \
		WPP_DEFINE_BIT(NDASSVC_NDASUNITDEVICE) \
		WPP_DEFINE_BIT(NDASSVC_NDASLOGDEVICE) \
		WPP_DEFINE_BIT(NDASSVC_SYSTEMUTIL) \
		WPP_DEFINE_BIT(NDASSVC_AUTOREG) \
		WPP_DEFINE_BIT(NDASSVC_HEARTBEAT) \
		WPP_DEFINE_BIT(NDASSVC_HIXUTIL) \
		WPP_DEFINE_BIT(NDASSVC_EVENTPUB) \
		WPP_DEFINE_BIT(NDASSVC_NDASCOMM) \
		WPP_DEFINE_BIT(NDASSVC_EVENTMON) \
		WPP_DEFINE_BIT(NDASSVC_IX) \
		WPP_DEFINE_BIT(NDASSVC_LPXCOMM) \
	)
