//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ndasmgmt.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_REGISTER_DEVICE             101
#define IDR_MAINFRAME                   128
#define IDS_NEW_DEVICE_NAME_TEMPLATE    129
#define IDS_OPTIONDLG_TITLE             130
#define IDS_NO_DEVICE                   131
#define IDS_DISABLE_DEVICE              132
#define ID_NDD_MOUNT_RO                 133
#define ID_NDD_MOUNT_RW                 134
#define IDS_UNMOUNT                     135
#define ID_NDD_UNMOUNT                  135
#define IDS_DEVICE_PROP_TITLE           136
#define DEVPROP_IDS_ADD_WRITE_KEY       137
#define DEVPROP_IDS_REMOVE_WRITE_KEY    138
#define DEVPROP_IDS_WRITE_KEY_PRESENT   139
#define DEVPROP_IDS_WRITE_KEY_NONE      140
#define IDS_NDAS_DEVICE_STATUS_CONNECTED 141
#define IDS_NDAS_DEVICE_STATUS_DISABLED 142
#define IDS_NDAS_DEVICE_STATUS_DISCONNECTED 143
#define IDS_NDAS_DEVICE_STATUS_UNKNOWN  144
#define IDS_BIG_BOLD_FONT_NAME          145
#define IDS_BIG_BOLD_FONT_SIZE          146
#define IDS_DRZ_INTRO_1                 147
#define IDS_DRZ_INTRO_TITLE             148
#define IDS_DRZ_DEVICE_NAME_HEADER_TITLE 149
#define IDS_DRZ_DEVICE_NAME_HEADER_SUBTITLE 150
#define IDS_DRZ_DEVICE_ID_HEADER_TITLE  151
#define IDS_DRZ_DEVICE_ID_HEADER_SUBTITLE 152
#define IDS_DRZ_TITLE                   153
#define IDS_DRZ_MOUNT_HEADER_TITLE      154
#define IDS_DRZ_MOUNT_HEADER_SUBTITLE   155
#define IDS_BT_RECONNECTING_INFO        156
#define IDS_BT_RECONNECTING_INFO_TITLE  157
#define IDS_BT_DISCONNECTED_INFO        158
#define IDS_BT_DISCONNECTED_INFO_TITLE  159
#define IDS_BT_RECONNECTED_INFO         160
#define IDS_BT_RECONNECTED_INFO_TITLE   161
#define IDS_UNITDEVICE_NONE             162
#define IDS_UNKNOWN_UNITDEVICE_TYPE     163
#define IDS_UNITDEVICE_STATUS_MOUNTED   164
#define IDS_UNITDEVICE_STATUS_NOT_MOUNTED 165
#define IDC_APPVER                      201
#define IDC_COMPVER                     202
#define IDC_LINK                        203
#define IDR_OPTION_GENERAL              203
#define IDC_APPNAME                     204
#define IDS_UNITDEVICE_STATUS_UNKNOWN   204
#define IDS_ENABLE_DEVICE               206
#define IDS_UNREGISTER_DEVICE           207
#define IDD_DEVICE_PROP_GENERAL         207
#define IDD_DEVPROP_GENERAL             207
#define IDD_DEVICE_PROP_HW              208
#define IDD_DEVPROP_HW                  208
#define IDD_RENAME                      209
#define IDB_ABOUT_HEADER                216
#define IDR_GIF1                        217
#define IDR_GIF2                        218
#define IDD_DRWZ_INTRO                  219
#define IDD_DEVREG_WIZARD_INTRO         219
#define IDD_DEVREG_WIZARD_WELCOME       219
#define IDD_DEVREG_WIZARD_COMPLETE      220
#define IDD_DEVREG_WIZARD_DEVICE_ID     221
#define IDB_WATERMARK16                 222
#define IDD_DEVREG_WIZARD_DEVICE_ID1    222
#define IDD_DEVREG_WIZARD_DEVICE_NAME   222
#define IDB_WATERMARK256                223
#define IDD_DEVREG_WIZARD_MOUNT         223
#define IDB_BANNER256                   224
#define IDB_BANNER16                    225
#define IDI_DISK_DRIVE                  226
#define IDI_DVD_DRIVE                   227
#define IDI_CD_DRIVE                    228
#define IDD_ADD_WRITE_KEY               230
#define IDD_DEVPROP_LOGDEV              231
#define ID_APP_OPTION                   300
#define IDR_TASKBAR                     400
#define IDS_DEVICE_PROPERTIES           401
#define IDS_SHOW_DEVICE_PROPERTIES      401
#define IDC_HEADER                      1000
#define IDC_DEVICE_ID                   1000
#define DEVPROP_IDC_DEVICE_ID           1000
#define IDC_CHECK1                      1001
#define DEVPROP_IDC_DEVICE_STATUS       1001
#define IDC_CHECK2                      1002
#define IDC_UILANG                      1003
#define IDC_DEV_ID_2                    1004
#define IDC_DEV_ID_1                    1005
#define IDC_DEV_ID_3                    1006
#define IDC_DEV_ID_4                    1007
#define IDC_DEV_KEY                     1008
#define IDC_DEV_NAME                    1010
#define IDC_REGISTER                    1011
#define IDC_DEVICE_NAME                 1012
#define IDC_LIST1                       1014
#define IDC_HWINFO_LIST                 1014
#define IDC_RENAME                      1015
#define DEVPROP_IDC_RENAME              1015
#define IDC_NEWNAME                     1016
#define IDC_NAME                        1016
#define DEVPROP_IDC_ADD_WRITE_KEY       1018
#define DEVPROP_IDC_DEVICE_WRITE_KEY    1019
#define DEVPROP_IDC_DEVICE_NAME         1020
#define IDC_INTRO_1                     1022
#define IDC_INTRO_2                     1023
#define IDC_BIG_BOLD_TITLE              1024
#define IDC_EDIT1                       1025
#define IDC_DEVICE_WRITE_KEY            1025
#define IDC_UNITDEVICE_STATUS           1025
#define IDC_EDIT2                       1026
#define IDC_RADIO1                      1026
#define IDC_MOUNT_RW                    1026
#define IDC_UNITDEVICE_MODEL            1026
#define IDC_EDIT3                       1027
#define IDC_RADIO2                      1027
#define IDC_MOUNT_RO                    1027
#define IDC_UNITDEVICE_TYPE_ICON        1027
#define IDC_EDIT4                       1028
#define IDC_RADIO3                      1028
#define IDC_DONT_MOUNT                  1028
#define IDC_UNITDEVICE_FWREV            1028
#define IDC_EDIT5                       1029
#define IDC_UNITDEVICE_SERIALNO         1029
#define IDC_UNITDEVICE_RO_HOSTS         1030
#define IDC_UNITDEVICE_RW_HOSTS         1031
#define IDC_UNITDEVICE_TYPE             1032
#define IDC_UNITDEVICE_CAPACITY         1033
#define IDC_TREE1                       1038
#define IDC_LOGDEV_TREE                 1038
#define IDB_STATUS_ENABLED_RW           6002
#define IDB_STATUS_ENABLED_RO           6003
#define IDB_STATUS_ERROR                6004
#define IDB_STATUS_BUSY                 6005
#define IDB_STATUS_DISABLED             6006
#define ID_NDAS_DEVICE_NONE             10001
#define ID_REGISTER_DEVICE              32775
#define ID_REFRESH_STATUS               32777
#define ID_ENABLE_DEVICE                0xE100
#define ID_DISABLE_DEVICE               0xE101
#define ID_UNREGISTER_DEVICE            0xE200
#define ID_SHOW_DEVICE_PROPERTIES       0xE300

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
