#ifndef _NDAS_TYPE_STR_H_
#define _NDAS_TYPE_STR_H_

#pragma once

//////////////////////////////////////////////////////////////////////////

#define BEGIN_ENUM_STRING(x) switch(x) {
#define ENUM_STRING(x) case x: {return TEXT(#x);}
#define ENUM_STRING_DEFAULT(x) default: {return TEXT(x);}
#define END_ENUM_STRING() }

//////////////////////////////////////////////////////////////////////////

__inline LPCTSTR NdasUnitDeviceTypeString(NDAS_UNITDEVICE_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_UNITDEVICE_TYPE_UNKNOWN)
		ENUM_STRING(NDAS_UNITDEVICE_TYPE_DISK)
		ENUM_STRING(NDAS_UNITDEVICE_TYPE_COMPACT_BLOCK)
		ENUM_STRING(NDAS_UNITDEVICE_TYPE_CDROM)
		ENUM_STRING(NDAS_UNITDEVICE_TYPE_OPTICAL_MEMORY)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_TYPE_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasUnitDeviceDiskTypeString(NDAS_UNITDEVICE_DISK_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_UNKNOWN)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_SINGLE)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_AGGREGATED)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_MIRROR_MASTER)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_MIRROR_SLAVE)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_RAID0)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_RAID1)
		ENUM_STRING(NDAS_UNITDEVICE_DISK_TYPE_RAID4)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_DISK_TYPE_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasUnitDeviceCDROMTypeString(NDAS_UNITDEVICE_CDROM_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_UNITDEVICE_CDROM_TYPE_UNKNOWN)
		ENUM_STRING(NDAS_UNITDEVICE_CDROM_TYPE_CD)
		ENUM_STRING(NDAS_UNITDEVICE_CDROM_TYPE_DVD)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_CDROM_TYPE_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasDeviceStatusString(NDAS_DEVICE_STATUS x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_DEVICE_STATUS_UNKNOWN)
		ENUM_STRING(NDAS_DEVICE_STATUS_DISABLED)
		ENUM_STRING(NDAS_DEVICE_STATUS_DISCONNECTED)
		ENUM_STRING(NDAS_DEVICE_STATUS_CONNECTED)
		ENUM_STRING_DEFAULT("NDAS_DEVICE_STATUS_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasDeviceErrorString(NDAS_DEVICE_ERROR x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_DEVICE_ERROR_NONE)
		ENUM_STRING(NDAS_DEVICE_ERROR_UNSUPPORTED_VERSION)
		ENUM_STRING(NDAS_DEVICE_ERROR_LPX_SOCKET_FAILED)
		ENUM_STRING(NDAS_DEVICE_ERROR_DISCOVER_FAILED)
		ENUM_STRING(NDAS_DEVICE_ERROR_LOGIN_FAILED)
		ENUM_STRING(NDAS_DEVICE_ERROR_FROM_SYSTEM)
		ENUM_STRING_DEFAULT("NDAS_DEVICE_ERROR_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasUnitDeviceStatusString(NDAS_UNITDEVICE_STATUS x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_UNITDEVICE_STATUS_UNKNOWN)
		ENUM_STRING(NDAS_UNITDEVICE_STATUS_NOT_MOUNTED)
		ENUM_STRING(NDAS_UNITDEVICE_STATUS_MOUNTED)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_STATUS_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasUnitDeviceErrorString(NDAS_UNITDEVICE_ERROR x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_UNITDEVICE_ERROR_NONE)
		ENUM_STRING_DEFAULT("NDAS_UNITDEVICE_ERROR_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasLogicalDeviceStatusString(NDAS_LOGICALDEVICE_STATUS x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_UNKNOWN)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_UNMOUNTED)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_MOUNT_PENDING)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_MOUNTED)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_UNMOUNT_PENDING)
		ENUM_STRING(NDAS_LOGICALDEVICE_STATUS_NOT_INITIALIZED)
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_STATUS_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasLogicalDeviceErrorString(NDAS_LOGICALDEVICE_ERROR x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_NONE)
		ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_FROM_DRIVER)
		ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_MISSING_MEMBER)
		ENUM_STRING(NDAS_LOGICALDEVICE_ERROR_INVALID_MEMBER)
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_ERROR_???")
	END_ENUM_STRING()
}

__inline LPCTSTR NdasLogicalDeviceTypeString(NDAS_LOGICALDEVICE_TYPE x)
{
	BEGIN_ENUM_STRING(x)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_DISK_SINGLE)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_DISK_MIRRORED)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_DISK_AGGREGATED)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_DISK_RAID0)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_DISK_RAID1)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_DISK_RAID4)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_DVD)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_VIRTUAL_DVD)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_MO)
		ENUM_STRING(NDAS_LOGICALDEVICE_TYPE_FLASHCARD)
		ENUM_STRING_DEFAULT("NDAS_LOGICALDEVICE_TYPE_???")
	END_ENUM_STRING()
}

//////////////////////////////////////////////////////////////////////////

#undef BEGIN_ENUM_STRING
#undef ENUM_STRING
#undef ENUM_STRING_DEFAULT
#undef END_ENUM_STRING

//////////////////////////////////////////////////////////////////////////

#endif /* _NDAS_TYPE_STR_H_ */
