#ifndef _NDASBIND_APP_INIT_ERR_RES_H_
#define _NDASBIND_APP_INIT_ERR_RES_H_
#pragma once

#define APP_INIT_MAX_TITLE_LEN		128
#define APP_INIT_MAX_MESSAGE_LEN	512

#define IDS_APP_INIT_ERROR_TITLE				400
#define IDS_APP_INIT_ERROR_OUT_OF_MEMORY		402
#define IDS_APP_INIT_ERROR_NO_RESOURCE			406
#define IDS_APP_INIT_ERROR_RESOURCE_LOAD		407

#endif // _APP_INIT_ERR_RES_H_
