!if 0
!if "$(DDK_TARGET_OS)"=="Win2K"
!message This component is not intended to target the Windows 2000 platform.
!elseif "$(DDK_TARGET_OS)"=="WinNET"
!message This component is not intended to target the Windows .NET platform.
!else
!INCLUDE $(NTMAKEENV)\makefile.def
!endif
!endif

!if "$(DDK_TARGET_OS)"=="Win2K"
!message This component is not intended to target the Windows 2000 platform.
!else
!INCLUDE $(NTMAKEENV)\makefile.def
!endif

