//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by nbres.rc
//
#ifdef IDC_STATIC
#undef IDC_STATIC
#endif
#define IDC_STATIC      (-1)
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141

#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDC_APPVER                      201
#define IDC_COMPVER                     202
#define IDC_LINK                        203
#define IDC_APPNAME                     204
#define IDI_NDAGGR_BROKEN               206
#define IDI_NDAGGR_OK                   207
#define IDI_ND_SLAVE                    210
#define IDI_ND_BADKEY                   211
#define IDI_ND_DISABLED                 212
#define IDI_ND_INUSE                    213
#define IDI_ND_NOEXIST                  214
#define IDI_ND_RO                       215
#define IDI_ND_RW                       216
#define IDB_ABOUT_HEADER                216
#define IDI_NDMIRR_OK                   219
#define IDI_NDMIRR_BROKEN               222
#define IDR_CONTEXT_MENU                223
#define IDD_UNBIND                      225
#define IDD_SYNC                        227
#define IDD_REMIRROR                    228
#define IDB_MAINFRAME                   228
#define IDD_REMIRROR_SYNC               228
#define IDD_REMIR                       229
#define IDR_MIRROR_MENU                 230
#define IDD_BIND_PAGE1                  234
#define IDD_BIND_PAGE2                  235
#define IDD_ADDMIRROR_SYNC              236
#define IDD_SELSOURCE                   237
#define IDD_PROPERTY_PAGE1              238
#define IDD_PROPERTY_PAGE2              239
#define IDD_ADDMIR                      240
#define IDD_PROPERTY_PAGE3              241
#define IDD_UNBIND1                     242
#define IDD_UNBIND_MIRROR               242
#define IDB_DRAG                        244
#define IDS_BINDPAGE_TOO_SMALL_NUMBER				245
#define IDS_BINDPAGE_TOO_LARGE_NUMBER				246
#define IDS_BINDPAGE_EVEN_NUMBER_FOR_MIRROR			247
#define IDS_BINDPAGE_TOTAL_SIZE_LIMIT				248
#define IDS_BIND_FAIL_AT_SINGLE_NDAS_FMT 360
#define IDS_BIND_FAIL 361
#define IDS_STATUS_REFRESH 366
#define IDS_MAINFRAME_SINGLE_ACCESS_FAIL 339
#define IDS_MAINFRAME_SERVICE_FAIL_AT_START			251
#define IDS_MAINFRAME_NO_DISK_TO_BIND				252
#define IDS_MAINFRAME_NOT_ENOUGH_DISK_TO_BIND		253
#define IDS_MAINFRAME_NO_DISK_TO_MIRROR				254
#define IDS_MAINFRAME_OLD_VERSION					255
#define IDS_MAINFRAME_SERVICE_FAIL					256
#define IDS_MAINFRAME_UNBIND_ACCESS_FAIL			257
#define IDS_MIRRORDLG_FAIL_TO_ACCESS_EXCLUSIVELY	258
#define IDS_MIRRORDLG_BTN_STOP						259
#define IDS_MIRRORDLG_BTN_OK						260
#define IDS_MIRRORDLG_BTN_RESUME					261
#define IDS_MIRRORDLG_CONNECT						262
#define IDS_MIRRORDLG_REBIND						263
#define IDS_MIRRORDLG_BIND							264
#define IDS_MIRRORDLG_RETRIEVE_BITMAP				265
#define IDS_MIRRORDLG_SYNCHRONIZE					266
#define IDS_MIRRORDLG_STOPPING						267
#define IDS_MIRRORDLG_FINISHED						268
#define IDS_MIRRORDLG_STOPPED						269
#define IDS_MIRRORDLG_FAIL_TO_MARK_BITMAP			270
#define IDS_MIRRORDLG_FAIL_TO_ADDMIRROR				271
#define IDS_MIRRORDLG_FAIL_TO_CONNECT				272
#define IDS_MIRRORDLG_FAIL_TO_READ_BITMAP			273
#define IDS_MIRRORDLG_FAIL_TO_UPDATE_BITMAP			274
#define IDS_MIRRORDLG_FAIL_TO_COPY					275
#define IDS_MIRRORDLG_FAIL_TO_CLEAR_DIRTYFLAG		276
#define IDS_MIRRORDLG_FAILED						278
#define IDS_DISKPROPERTYPAGE_MIGRATE_DISK_NOT_EXIST	279
#define IDS_DISKPROPERTYPAGE_MIGRATE_CONFIRM		280
#define IDS_DISKPROPERTYPAGE_MIGRATE_ACCESS_FAIL	281
#define IDS_DISKPROPERTYPAGE_MIGRATE_FAIL			282
#define IDS_DISKPROPERTYPAGE_MIGRATE_FAIL_AT_FMT		367
#define IDS_DISKPROPERTYPAGE_MIGRATE_SUCCESS		283
#define IDS_DISKPROPERTYPAGE_WRITEKEY_PRESENT		284
#define IDS_DISKPROPERTYPAGE_WRITEKEY_NOT_PRESENT	285
#define IDS_DISKPROPERTYPAGE_SIZE_IN_GB				286
#define IDS_DISKPROPERTYPAGE_LIST_COL_NAME			287
#define IDS_DISKPROPERTYPAGE_LIST_COL_VALUE			288
#define IDS_SELECTMIRDLG_NO_DISK_SELECTED			289
#define IDS_SELECTMIRDLG_SMALLER_DISK				290
#define IDS_ERROR_TITLE 338
#define IDS_ERROR_NDAS_DESCRIPTION_FMT 345
#define IDS_ERROR_SYSTEM_DESCRIPTION_FMT 346
#define IDS_ERROR_NOT_REGISTERD_WRITE_FMT 352
#define IDS_WARNING_NOT_NEED_RECOVER 384
#define IDS_WARNING_BIND 347
#define IDS_WARNING_BIND_AFTER 348
#define IDS_WARNING_UNBIND 357
#define IDS_WARNING_UNBIND_AFTER 358
#define IDS_WARNING_ADD_MIRROR 385
#define IDS_WARNING_SINGLE 336
#define IDS_WARNING_SINGLE_AFTER 337
#define IDD_ERROR 340
#define IDC_ERROR_ICON 341
#define IDC_ERROR_DESCRIPTION 342
#define IDC_ERROR_MESSAGE 343
#define IDD_WAIT 363
#define IDC_WAIT_MESSAGE 364
#define IDC_WAIT_ICON 365
#define IDC_LAST_ERROR_MESSAGE 362
#define IDS_UIHANDLER_PROPERTY_NUM_BOUND_DISK		291
#define IDS_UIHANDLER_PROPERTY_NUM_BOUND_DISK_TOOLTIP	292
#define IDS_UIHANDLER_PROPERTY_DIRTY				293
#define IDS_UIHANDLER_PROPERTY_DIRTY_TRUE			294
#define IDS_UIHANDLER_PROPERTY_DIRTY_FALSE			295
#define IDS_UIHANDLER_PROPERTY_DIRTY_TOOLTIP		296
#define IDS_UIHANDLER_CLEARDIB_FAIL					297
#define IDS_UIHANDLER_CLEARDIB_SUCCESS				298
#define IDS_UIHANDLER_PROPERTY_MODEL				299
#define IDS_UIHANDLER_PROPERTY_MODEL_TOOLTIP		300
#define IDS_UIHANDLER_PROPERTY_SERIALNO				301
#define IDS_UIHANDLER_PROPERTY_SERIALNO_TOOLTIP		302
#define IDS_UIHANDLER_CLEARDIB_CONFIRM				303
#define IDS_UIHANDLER_CLEARDIB_ACCESS_FAIL			304
#define IDS_UNBINDDLG_ACCESS_FAIL					305
#define IDS_UNBIDNDLG_FAIL							306
#define IDS_DISKPROPERTYPAGE_GENERALTAB				307
#define IDS_DISKPROPERTYPAGE_HARDWARETAB			308
#define IDS_ABOUTDLG_PRODUCT_NAME					309
#define IDS_ABOUTDLG_PRODUCT_VER					310
#define IDS_ABOUTDLG_COL_COMPONENT					311
#define IDS_ABOUTDLG_COL_VERSION					312
#define IDS_ABOUTDLG_COMPONENT_VER					313
#define IDS_LISTVIEW_SIZE_IN_GB						314
#define IDS_LISTVIEW_COL_NAME						315
#define IDS_LISTVIEW_COL_ID							316
#define IDS_LISTVIEW_COL_SIZE						317
#define IDS_LISTVIEW_COL_EMPTY						318
#define IDS_COMMAND_BIND							319
#define IDS_COMMAND_UNBIND							320
#define IDS_COMMAND_SYNCHRONIZE						321
#define IDS_COMMAND_REMIRROR						322
#define IDS_COMMAND_ADDMIRROR						323
#define IDS_COMMAND_CLEARDIB						324
#define IDS_COMMAND_SINGLE        335
#define IDS_APPLICATION						      326
#define IDS_BINDPAGE_CAPTION          327
#define IDS_DISKPROPERTYPAGE_CAPTION  329
#define IDS_BINDPAGE_FAIL_TO_BIND_DISK 330
#define IDS_BINDPAGE_DISK_COUNT_AGGR 331
#define IDS_BINDPAGE_DISK_COUNT_RAID0 332
#define IDS_BINDPAGE_DISK_COUNT_RAID1 333
#define IDS_BINDPAGE_DISK_COUNT_RAID4 334
#define IDC_DEVICE_ID 383
#define IDS_LOGDEV_TYPE 368
#define IDS_LOGDEV_TYPE_DISK_RAID0 369
#define IDS_LOGDEV_TYPE_DISK_RAID1 370
#define IDS_LOGDEV_TYPE_DISK_RAID2 371
#define IDS_LOGDEV_TYPE_DISK_RAID3 372
#define IDS_LOGDEV_TYPE_DISK_RAID4 373
#define IDS_LOGDEV_TYPE_DISK_RAID5 374
#define IDS_LOGDEV_TYPE_AGGREGATED_DISK 375
#define IDS_LOGDEV_TYPE_CF_DRIVE 376
#define IDS_LOGDEV_TYPE_DVD_DRIVE 377
#define IDS_LOGDEV_TYPE_MIRRORED_DISK 378
#define IDS_LOGDEV_TYPE_MO_DRIVE 379
#define IDS_LOGDEV_TYPE_SINGLE_DISK 380
#define IDS_LOGDEV_TYPE_UNKNOWN_FMT 381
#define IDS_LOGDEV_TYPE_VIRTUAL_DVD_DRIVE 382
#define IDS_UNIDEV_TYPE_DISK_EMPTY 386

// last number 386

#define IDC_MAINDLG_AGGR_BINDBTN        1000
#define IDC_MAINDLG_MIRR_BINDBTN        1001
#define IDC_MAINDLG_AGGR_UNBINDBTN      1002
#define IDC_MAINDLG_RELOAD              1003
#define IDC_TREE_NETDISK                1004
#define IDC_LIST_SINGLE                 1010
#define IDC_LIST_MIRROR                 1011
#define IDC_LIST_PRIMARY                1012
#define IDC_CHK_MIRROR                  1013
#define IDC_BTN_TO_PRIMARY              1014
#define IDC_BTN_FROM_PRIMARY            1015
#define IDC_BTN_TO_MIRROR               1016
#define IDC_BTN_FROM_MIRROR             1017
#define IDC_LIST_UNBIND                 1020
#define IDC_TEXT_ELAPSEDTIME            1021
#define IDC_TEXT_LEFTTIME               1022
#define IDC_TEXT_RATE                   1023
#define IDC_PROGBAR_JOB                 1024
#define IDC_PROGBAR                     1024
#define IDC_TEXT_SOURCE                 1028
#define IDC_TEXT_DEST                   1029
#define IDC_TEXT_PHASE                  1030
#define IDC_PRODUCTVER                  1031
#define IDC_TEXT_PRODUCTVER             1031
#define IDC_FILEVER                     1032
#define IDC_TEXT_FILEVER                1032
#define IDC_ABOUTBOX_HYPERLINK          1033
#define IDI_COMPANY                     1034
#define IDC_TEXT_COPYWRITE              1035
#define IDC_EDIT_DISKCOUNT              1051
#define IDC_BTN_ADD                     1052
#define IDC_BTN_REMOVE                  1053
#define IDC_LIST_BIND                   1054
#define IDC_TYPE                        1055
#define IDC_BTN_UP                      1055
#define IDC_TYPE2                       1056
#define IDC_BTN_DOWN                    1056
#define IDC_EDIT2                       1057
#define IDC_EDIT3                       1058
#define IDC_BUTTON1                     1059
#define IDC_BTN_MIGRATE                 1059
#define IDC_BUTTON2                     1060
#define IDC_DISKLIST                    1062
#define IDC_EDIT_NAME                   1063
#define IDC_LIST_PROPERTY               1064
#define IDC_COPYWRITE                   1065
#define IDC_EDIT_ID                     1066
#define IDC_IMAGE                       1066
#define IDC_EDIT_WRITEKEY               1067
#define IDC_TREE1                       1067
#define IDC_EDIT_CAPACITY               1068
#define IDC_ST_MIGRATE                  1069
#define IDC_TEXT_MIGRATE                1070
#define IDC_BIND_TYPE_AGGR              1057
#define IDC_BIND_TYPE_RAID0             1071
#define IDC_BIND_TYPE_RAID1             1072
#define IDC_BIND_TYPE_RAID4             1073

#define IDM_EXIT                        32773
#define IDM_AGGR_BIND                   32774
#define IDM_AGGR_UNBIND                 32776
#define IDM_AGGR_SINGLE                 32777
#define IDM_AGGR_SYNCHRONIZE            32779
#define IDM_AGGR_REMIRROR               32780
#define IDM_AGGR_MIRROR                 32781
#define IDM_HELP_ABOUT                  32782
#define IDM_AGGR_CLEARDIB               32783
#define IDM_AGGR_ADDMIRROR              32791
#define IDM_AGGR_REFRESH                32792
#define IDM_AGGR_PROPERTY               32793
#define IDM_REFRESH_STATUS              32794
#define ID_CONTEXT                      32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        325
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
