// ndasbind.h
#pragma once

#define WM_APP_NDAS_DEVICE_STATUS_CHANGED		(WM_APP + 0x980)
#define WM_APP_NDAS_LOGICALDEVICE_STATUS_CHANGED	(WM_APP + 0x981)
#define WM_APP_NDAS_DEVICE_ENTRY_CHANGED		(WM_APP + 0x982)
#define WM_APP_NDAS_LOGICALDEVICE_ENTRY_CHANGED	(WM_APP + 0x983)
#define WM_APP_NDAS_SURRENDER_ACCESS_REQUEST	(WM_APP + 0x984)
#define WM_APP_NDAS_DEVICE_PROPERTY_CHANGED		(WM_APP + 0x985)
#define WM_APP_NDAS_UNITDEVICE_PROPERTY_CHANGED	(WM_APP + 0x986)
#define WM_APP_NDAS_LOGICALDEVICE_DISCONNECTED	(WM_APP + 0x990)
#define WM_APP_NDAS_LOGICALDEVICE_RECONNECTING	(WM_APP + 0x991)
#define WM_APP_NDAS_LOGICALDEVICE_RECONNECTED	(WM_APP + 0x992)
#define WM_APP_NDAS_SERVICE_TERMINATING (WM_APP + 0x993)
