/*++

Copyright (C) 2002-2004 XIMETA, Inc.
All rights reserved.

--*/
#ifndef _SCRC32_H_
#define _SCRC32_H_
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

unsigned int 
__cdecl 
crc32_calc(const unsigned char* p, size_t len);

#ifdef __cplusplus
}
#endif

#endif /* _SCRC32_H_ */
 
/* DO NOT EDIT THIS FILE HERE */ 
/* This is a copied header from the project */ 
/* Any modification will be overwritten by the project compilation */ 
 
