//
// Software Tracing Definitions 
//
// {54D7F219-450D-4279-BF8D-84004D59CF59}
#define NDASPORT_WPP_CONTROL_GUIDS \
	WPP_DEFINE_CONTROL_GUID(NdasPortTraceGuid,(54D7F219,450D,4279,BF8D,84004D59CF59),  \
	WPP_DEFINE_BIT(NDASPORT_GENERAL) \
	WPP_DEFINE_BIT(NDASPORT_POWER) \
	WPP_DEFINE_BIT(NDASPORT_FDO_GENERAL) \
	WPP_DEFINE_BIT(NDASPORT_FDO_PNP) \
	WPP_DEFINE_BIT(NDASPORT_FDO_IOCTL) \
	WPP_DEFINE_BIT(NDASPORT_FDO_SCSI) \
	WPP_DEFINE_BIT(NDASPORT_PDO_GENERAL) \
	WPP_DEFINE_BIT(NDASPORT_PDO_PNP) \
	WPP_DEFINE_BIT(NDASPORT_PDO_IOCTL) \
	WPP_DEFINE_BIT(NDASPORT_PDO_SCSI) \
	WPP_DEFINE_BIT(NDASPORT_PDO_SCSIEX) \
	WPP_DEFINE_BIT(NDASPORT_LSPIO) \
	WPP_DEFINE_BIT(NDASPORT_SRB) \
	)

#define NDASDISK_WPP_CONTROL_GUIDS \
	WPP_DEFINE_CONTROL_GUID(NdasAtaDeviceTraceGuid,(9FE34864,4639,42b3,8032,20E9AD73FCA1),  \
	WPP_DEFINE_BIT(NDASATA_INIT) \
	WPP_DEFINE_BIT(NDASATA_PROP) \
	WPP_DEFINE_BIT(NDASATA_IO) \
	)

#define FILEDISK_WPP_CONTROL_GUIDS \
	WPP_DEFINE_CONTROL_GUID(NdasFileDiskTraceGuid,(9FE34861,4639,42b3,8032,20E9AD73FCA1),  \
	WPP_DEFINE_BIT(FILEDISK_INIT) \
	WPP_DEFINE_BIT(FILEDISK_PROP) \
	WPP_DEFINE_BIT(FILEDISK_IO) \
	)

#define RAMDISK_WPP_CONTROL_GUIDS \
	WPP_DEFINE_CONTROL_GUID(NdasRamDiskTraceGuid,(9FE34862,4639,42b3,8032,20E9AD73FCA1),  \
	WPP_DEFINE_BIT(RAMDISK_INIT) \
	WPP_DEFINE_BIT(RAMDISK_PROP) \
	WPP_DEFINE_BIT(RAMDISK_IO) \
	)
