//
// Do not edit this file from the Visual Studio Resource Editor
//
#ifndef APSTUDIO_INVOKED
#include <windows.h>
#include "ndasmgmt_appiniterr.h"

#pragma code_page(1252)

LANGUAGE LANG_ITALIAN, SUBLANG_ITALIAN
STRINGTABLE
BEGIN
	IDS_APP_INIT_ERROR_TITLE				"Errore di inzializzazione applicazione"
	IDS_APP_INIT_ERROR_ADMIN_PRIV_REQUIRED	"Questa applicazione richiede privilegi di amministratore.\r\nAccedere in qualità di utente in un gruppo di Amministratori ed eseguire nuovamente l'applicazione."
	IDS_APP_INIT_ERROR_OUT_OF_MEMORY		"L'applicazione non può avviarsi per il motivo seguente.\r\nMemoria insufficiente.\r\nChiudere le altre applicazioni e riprovare."
	IDS_APP_INIT_ERROR_NO_NDASUSER			"Caricamento di NDASUSER.DLL non riuscito.\r\nVerificare il software installato."
	IDS_APP_INIT_ERROR_INVALID_NDASUSER		"NDASUSER.DLL non valido installato.\r\nVerificare il software installato."
	IDS_APP_INIT_ERROR_CREATE_WINDOW		"Creazione di una finestra non riuscita. La memoria del sistema va esaurendosi.\r\nChiudere le altre applicazioni e riprovare."
	IDS_APP_INIT_ERROR_NO_RESOURCE			"Risorse DLL compatibili non disponibili.\r\nVerificare l'installazione del software."
	IDS_APP_INIT_ERROR_RESOURCE_LOAD		"Impossibile caricare la risorsa DLL.\r\nVerificare l'installazione del software."
END

#endif // APSTUDIO_INVOKED
