//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ndasmgmt.rc
//
#ifdef IDC_STATIC
#undef IDC_STATIC
#endif
#define IDC_STATIC      (-1)
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_FILE_NEW						0xE100

#define IDB_ABOUT_HEADER                101
#define IDB_BANNER16                    102
#define IDB_BANNER256                   103
#define IDB_PROPTREE                    104
#define IDB_STATUS_BUSY                 105
#define IDB_STATUS_DISABLED             106
#define IDB_STATUS_ENABLED_RO           107
#define IDB_STATUS_ENABLED_RW           108
#define IDB_STATUS_ERROR                109
#define IDB_WATERMARK16                 110
#define IDB_WATERMARK256                111
#define IDI_CD_DRIVE                    201
#define IDI_DISK_DRIVE                  202
#define IDI_DVD_DRIVE                   203
#define IDD_ABOUTBOX                    301
#define IDD_ADD_WRITE_KEY               302
#define IDD_CONFIRM                     303
#define IDD_DEVICE_PROP_GENERAL         304
#define IDD_DEVICE_PROP_HW              305
#define IDD_DEVPROP_GENERAL             306
#define IDD_DEVPROP_HOSTINFO            307
#define IDD_DEVPROP_HW                  308
#define IDD_DEVPROP_LOGDEV              309
#define IDD_DEVREG_WIZARD_COMPLETE      310
#define IDD_DEVREG_WIZARD_DEVICE_ID     311
#define IDD_DEVREG_WIZARD_DEVICE_ID1    312
#define IDD_DEVREG_WIZARD_DEVICE_NAME   313
#define IDD_DEVREG_WIZARD_INTRO         314
#define IDD_DEVREG_WIZARD_MOUNT         315
#define IDD_DEVREG_WIZARD_WELCOME       316
#define IDD_DRWZ_INTRO                  317
#define IDD_ERROR                       318
#define IDD_OPTION_ADVANCED             319
#define IDD_PROPPAGE_LARGE              320
#define IDD_REGISTER_DEVICE             321
#define IDD_RENAME                      322
#define IDD_WAIT                        323
#define IDD_WORKING                     324
#define IDC_ADD_WRITE_KEY               1001
#define IDC_ALERT_DISCONNECT            1002
#define IDC_ALERT_RECONNECT             1003
#define IDC_PRODNAME                    1004
#define IDC_PRODVER                     1005
#define IDC_BIG_BOLD_TITLE              1006
#define IDC_COMPLETE_MESSAGE            1007
#define IDC_COMPVER                     1008
#define IDC_CONFIRM_ICON                1009
#define IDC_CONFIRM_MESSAGE             1010
#define IDC_DEVICE_ID                   1011
#define IDC_DEVICE_NAME                 1012
#define IDC_DEVICE_STATUS               1013
#define IDC_DEVICE_WRITE_KEY            1014
#define IDC_DEV_ID_1                    1015
#define IDC_DEV_ID_2                    1016
#define IDC_DEV_ID_3                    1017
#define IDC_DEV_ID_4                    1018
#define IDC_DEV_KEY                     1019
#define IDC_DEV_NAME                    1020
#define IDC_DONT_MOUNT                  1021
#define IDC_DONT_SHOW_AGAIN             1022
#define IDC_DONT_SHOW_REGWIZ            1023
#define IDC_ENABLE_DEVICE               1024
#define IDC_ERROR_DESCRIPTION           1025
#define IDC_ERROR_ICON                  1026
#define IDC_ERROR_MESSAGE               1027
#define IDC_HEADER                      1028
#define IDC_HIDDEN                      1029
#define IDC_HOST_LIST                   1030
#define IDC_HWINFO_LIST                 1031
#define IDC_INTRO_1                     1032
#define IDC_INTRO_2                     1033
#define IDC_LINK                        1034
#define IDC_LOGDEV_TREE                 1035
#define IDC_MOUNT_QUESTION              1036
#define IDC_MOUNT_RO                    1037
#define IDC_MOUNT_RW                    1038
#define IDC_MOUNT_STATUS                1039
#define IDC_MOUNT_WARNING               1040
#define IDC_NAME                        1041
#define IDC_NEWNAME                     1042
#define IDC_OPTION_TREE                 1043
#define IDC_PROGRESS_MESSAGE            1044
#define IDC_PROPLIST                    1045
#define IDC_REGISTER                    1046
#define IDC_REMOUNT_ON_BOOT             1047
#define IDC_RENAME                      1048
#define IDC_UILANG                      1049
#define IDC_UNITDEVICE_CAPACITY         1050
#define IDC_UNITDEVICE_FWREV            1051
#define IDC_UNITDEVICE_MODEL            1052
#define IDC_UNITDEVICE_RO_HOSTS         1053
#define IDC_UNITDEVICE_RW_HOSTS         1054
#define IDC_UNITDEVICE_SERIALNO         1055
#define IDC_UNITDEVICE_STATUS           1056
#define IDC_UNITDEVICE_TYPE             1057
#define IDC_UNITDEVICE_TYPE_ICON        1058
#define IDC_WAIT_MESSAGE                1059
#define IDR_APP_OPTION                  2001
#define IDR_DISABLE_DEVICE              2002
#define IDR_ENABLE_DEVICE               2003
#define IDR_MAINFRAME                   2004
#define IDR_NDAS_DEVICE_NONE            2005
#define IDR_NDD_MOUNT_RO                2006
#define IDR_NDD_MOUNT_RW                2007
#define IDR_NDD_UNMOUNT                 2008
#define IDR_OPTION_GENERAL              2009
#define IDR_REFRESH_STATUS              2010
#define IDR_REGISTER_DEVICE             2011
#define IDR_SHOW_DEVICE_PROPERTIES      2012
#define IDR_TASKBAR                     2013
#define IDR_UNMOUNT_ALL                 2014
#define IDR_UNREGISTER_DEVICE           2015
#define IDS_ABOUTDLG_HYPERLINK          3001
#define IDS_ADD_WRITE_KEY               3002
#define IDS_ASK_SURRENDER_REQUEST_FMT   3003
#define IDS_BIG_BOLD_FONT_NAME          3004
#define IDS_BIG_BOLD_FONT_SIZE          3005
#define IDS_BT_DISCONNECTED_INFO        3006
#define IDS_BT_DISCONNECTED_INFO_TITLE  3007
#define IDS_BT_RECONNECTED_INFO         3008
#define IDS_BT_RECONNECTED_INFO_TITLE   3009
#define IDS_BT_RECONNECTING_INFO        3010
#define IDS_BT_RECONNECTING_INFO_TITLE  3011
#define IDS_BT_EMERGENCY_INFO           3175
#define IDS_BT_EMERGENCY_INFO_TITLE     3176
#define IDS_CONFIRM_EXIT                3012
#define IDS_CONFIRM_UNMOUNT             3013
#define IDS_CONFIRM_UNMOUNT_ALL         3014
#define IDS_CONFIRM_UNMOUNT_FMT         3015
#define IDS_CONFIRM_UNREGISTER          3016
#define IDS_CONFIRM_UNREGISTER_FMT      3017
#define IDS_DEVICE_PROPERTIES           3018
#define IDS_DEVICE_PROP_TITLE           3019
#define IDS_DEVMST_CONNECTED            3020
#define IDS_DEVMST_CONNECTED_MOUNTED_ANOTHER 3021
#define IDS_DEVMST_DEACTIVATED          3022
#define IDS_DEVMST_DISCONNECTED         3023
#define IDS_DEVMST_ERROR                3024
#define IDS_DEVMST_MOUNTED_RO           3025
#define IDS_DEVMST_MOUNTED_RW           3026
#define IDS_DEVMST_UNKNOWN              3027
#define IDS_DEVPROP_CATEGORY_HARDWARE   3028
#define IDS_DEVPROP_HW_MAX_LU_COUNT     3029
#define IDS_DEVPROP_HW_MAX_REQUEST_BLOCKS 3030
#define IDS_DEVPROP_HW_MAX_TARGET_COUNT 3031
#define IDS_DEVPROP_HW_SLOT_COUNT       3032
#define IDS_DEVPROP_HW_TARGET_COUNT     3033
#define IDS_DEVPROP_HW_VERSION          3034
#define IDS_DEVPROP_UNITDEV_DEVICE_TYPE 3035
#define IDS_DEVPROP_UNITDEV_FWREV       3036
#define IDS_DEVPROP_UNITDEV_LBA_MODE    3037
#define IDS_DEVPROP_UNITDEV_MODEL       3038
#define IDS_DEVPROP_UNITDEV_SERIALNO    3039
#define IDS_DEVPROP_UNITDEV_TITLE_FMT   3040
#define IDS_DEVPROP_UNITDEV_TRANSFER_MODE 3041
#define IDS_DEVWIZ_MOUNT_STATUS_NORMAL  3042
#define IDS_DEVWIZ_MOUNT_STATUS_WAIT    3043
#define IDS_DISABLE_DEVICE              3044
#define IDS_DRZ_DEVICE_ID_HEADER_SUBTITLE 3045
#define IDS_DRZ_DEVICE_ID_HEADER_TITLE  3046
#define IDS_DRZ_DEVICE_NAME_HEADER_SUBTITLE 3047
#define IDS_DRZ_DEVICE_NAME_HEADER_TITLE 3048
#define IDS_DRZ_INTRO_1                 3049
#define IDS_DRZ_INTRO_TITLE             3050
#define IDS_DRZ_MOUNT_HEADER_SUBTITLE   3051
#define IDS_DRZ_MOUNT_HEADER_TITLE      3052
#define IDS_DRZ_TITLE                   3053
#define IDS_ENABLE_DEVICE               3054
#define IDS_ERROR_ADD_WRITE_KEY         3055
#define IDS_ERROR_DISABLE_DEVICE        3056
#define IDS_ERROR_ENABLE_DEVICE         3057
#define IDS_ERROR_MOUNT_DEVICE_RO       3058
#define IDS_ERROR_MOUNT_DEVICE_RW       3059
#define IDS_ERROR_NDAS_DESCRIPTION_FMT  3060
#define IDS_ERROR_REGISTER_DEVICE_FAILURE 3061
#define IDS_ERROR_REMOVE_WRITE_KEY      3062
#define IDS_ERROR_RENAME_DEVICE         3063
#define IDS_ERROR_SYSTEM_DESCRIPTION_FMT 3064
#define IDS_ERROR_TITLE                 3065
#define IDS_ERROR_UNMOUNT_DEVICE        3066
#define IDS_ERROR_UNREGISTER_DEVICE     3067
#define IDS_ERROR_UPDATE_DEVICE_LIST    3068
#define IDS_INVALID_DEVICE_ID_TOOLTIP_TEXT 3069
#define IDS_INVALID_DEVICE_ID_TOOLTIP_TITLE 3070
#define IDS_KNOWN_NDAS_HOST             3071
#define IDS_LANG_AUTO                   3072
#define IDS_LANG_CHANGE                 3073
#define IDS_LOGDEV_INFO_UNAVAILABLE     3083
#define IDS_LOGDEV_LOCATION             3084
#define IDS_LOGDEV_LOCATION_FMT         3085
#define IDS_LOGDEV_STATUS_MOUNTED_RO    3086
#define IDS_LOGDEV_STATUS_MOUNTED_RW    3087
#define IDS_LOGDEV_STATUS_MOUNT_PENDING 3088
#define IDS_LOGDEV_STATUS_NOT_MOUNTABLE 3089
#define IDS_LOGDEV_STATUS_UNKNOWN_FMT   3090
#define IDS_LOGDEV_STATUS_UNMOUNTED     3091
#define IDS_LOGDEV_STATUS_UNMOUNT_PENDING 3092
#define IDS_LOGDEV_TYPE_AGGREGATED_DISK 3093
#define IDS_LOGDEV_TYPE_CF_DRIVE        3094
#define IDS_LOGDEV_TYPE_DVD_DRIVE       3096
#define IDS_LOGDEV_TYPE_MIRRORED_DISK   3097
#define IDS_LOGDEV_TYPE_MO_DRIVE        3098
#define IDS_LOGDEV_TYPE_SINGLE_DISK     3099
#define IDS_LOGDEV_TYPE_UNKNOWN_FMT     3100
#define IDS_LOGDEV_TYPE_VIRTUAL_DVD_DRIVE 3101
#define IDS_MAIN_TITLE                  3102
#define IDS_NDAS_DEVICE_STATUS_CONNECTED 3103
#define IDS_NDAS_DEVICE_STATUS_DISABLED 3104
#define IDS_NDAS_DEVICE_STATUS_DISCONNECTED 3105
#define IDS_NDAS_DEVICE_STATUS_UNKNOWN  3106
#define IDS_NEW_DEVICE_NAME_TEMPLATE    3107
#define IDS_NO_DEVICE                   3108
#define IDS_OG_DONT_CONFIRM_EXIT        3109
#define IDS_OG_MENU_DISPLAY_STATUS_TEXT 3110
#define IDS_OG_MENU_DISPLAY_UNMOUNT_ALL 3111
#define IDS_OPTIONDLG_TITLE             3112
#define IDS_OPTION_GROUP_CONFIRM        3113
#define IDS_OPTION_GROUP_MENU           3114
#define IDS_REGWIZ_COMPLETE_NORMAL      3115
#define IDS_REGWIZ_COMPLETE_NOT_CONNECTED 3116
#define IDS_REGWIZ_COMPLETE_NOT_MOUNTABLE 3117
#define IDS_REMOVE_WRITE_KEY            3118
#define IDS_REMOVE_WRITE_KEY_CONFIRM    3119
#define IDS_REMOVE_WRITE_KEY_CONFIRM_TITLE 3120
#define IDS_REQUEST_SURRENDER_RW_ACCESS 3121
#define IDS_SHOW_DEVICE_PROPERTIES      3122
#define IDS_SURRENDER_REQUEST_CONNECTING 3123
#define IDS_SURRENDER_REQUEST_WAITING   3124
#define IDS_UNITDEVICE_NONE             3125
#define IDS_UNITDEVICE_PROP_TITLE_FMT   3126
#define IDS_UNITDEVICE_STATUS_MOUNTED   3127
#define IDS_UNITDEVICE_STATUS_NOT_MOUNTED 3128
#define IDS_UNITDEVICE_STATUS_UNKNOWN   3129
#define IDS_UNITDEVICE_STATUS_UNKNOWN_FMT 3130
#define IDS_UNITDEV_MEDIA_TYPE_CDROM    3131
#define IDS_UNITDEV_MEDIA_TYPE_COMPACT_FLASH 3132
#define IDS_UNITDEV_MEDIA_TYPE_DISK     3133
#define IDS_UNITDEV_MEDIA_TYPE_OPMEM    3134
#define IDS_UNITDEV_MEDIA_TYPE_UNKNOWN_FMT 3135
#define IDS_UNITDEV_TYPE_CDROM          3136
#define IDS_UNITDEV_TYPE_DISK           3137
#define IDS_UNITDEV_TYPE_DISK_AGGREGATED 3138
#define IDS_UNITDEV_TYPE_DISK_MIRROR_MASTER 3139
#define IDS_UNITDEV_TYPE_DISK_MIRROR_SLAVE 3140
#define IDS_UNITDEV_TYPE_DISK_SINGLE    3141
#define IDS_UNITDEV_TYPE_DISK_UNKNOWN_FMT 3142
#define IDS_UNITDEV_TYPE_UNKNOWN_FMT    3143
#define IDS_UNKNOWN_UNITDEVICE_TYPE     3144
#define IDS_UNREGISTER_DEVICE           3145
#define IDS_WRITE_KEY_NONE              3146
#define IDS_WRITE_KEY_PRESENT           3147
#define IDS_OG_DONT_CONFIRM_REMOVE_WRITE_KEY 3148
#define IDS_OG_DONT_CONFIRM_UNREGISTER  3149
#define IDS_OG_DONT_CONFIRM_UNMOUNT     3150
#define IDS_OG_DONT_CONFIRM_UNMOUNT_ALL 3151
#define IDS_OG_MENU_USE_REG_WIZARD      3152
#define IDS_NDASMGMT_WELCOME_TOOLTIP    3153
#define IDS_NDASMGMT_WELCOME_TITLE      3154
#define IDS_NDASMGMT_ALREADY_RUNNING_TOOLTIP 3155
#define IDS_NDASMGMT_ALREADY_RUNNING_TITLE 3156
#define IDS_HOSTSTAT_ACCESS             3157
#define IDS_HOSTSTAT_HOSTNAME           3158
#define IDS_HOSTSTAT_NETWORK_ADDRESS    3159
#define IDS_LOGICALDEVICE_ENTRY_FMT     3160
#define IDS_LOGICALDEVICE_ENTRY_MISSING_FMT 3161
#define IDS_LOGICALDEVICE_ENTRY_UNAVAILABLE_FMT 3162
#define IDS_WAIT_MOUNT                  3163
#define IDS_WAIT_UNMOUNT                3164
#define IDS_LANGUAGE_CHANGE             3165
#define IDS_OPTION_GROUP_SUSPEND        3166
#define IDS_OG_SUSPEND_ALLOW            3167
#define IDS_OG_SUSPEND_DENY             3169
#define IDS_SUSPEND_WARNING             3170
#define IDS_ACTIVATE_DEVICE             3171
#define IDS_ERROR_RESET_DEVICE          3172
#define IDS_CONFIRM_DEACTIVATE_DEVICE   3173
#define IDS_CONFIRM_RESET_DEVICE        3174
#define IDS_ABOUTDLG_COL_COMPONENT		3177
#define IDS_ABOUTDLG_COL_VERSION		3178
#define IDD_DEVICE_AVAIL                4001
#define IDD_DEVPROP_ADVANCED            4002
#define IDS_LOGDEV_TYPE_DISK_RAID0      4100
#define IDS_LOGDEV_TYPE_DISK_RAID1      4101
#define IDS_LOGDEV_TYPE_DISK_RAID2      4102
#define IDS_LOGDEV_TYPE_DISK_RAID3      4103
#define IDS_LOGDEV_TYPE_DISK_RAID4      4104
#define IDS_LOGDEV_TYPE_DISK_RAID5      4105
#define IDS_UNITDEV_TYPE_DISK_RAID0     4110
#define IDS_UNITDEV_TYPE_DISK_RAID1     4111
#define IDS_UNITDEV_TYPE_DISK_RAID2     4112
#define IDS_UNITDEV_TYPE_DISK_RAID3     4113
#define IDS_UNITDEV_TYPE_DISK_RAID4     4114
#define IDS_UNITDEV_TYPE_DISK_RAID5     4115
#define IDS_WAIT_CHECK_UPDATE           4116
#define IDS_ERROR_CHECK_UPDATE          4117
#define IDC_WAIT_ICON                   5001
#define IDC_CHECK_UPDATE                5003
#define IDC_DEACTIVATE_DEVICE           5004
#define IDC_BUTTON1                     5005
#define IDC_RESET_DEVICE                5005
#define IDS_CURRENT_LANGUAGE            9999

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        4002
#define _APS_NEXT_COMMAND_VALUE         33000
#define _APS_NEXT_CONTROL_VALUE         5006
#define _APS_NEXT_SYMED_VALUE           6001
#endif
#endif
