/*++

Copyright (C)2002-2005 XIMETA, Inc.
All rights reserved.

--*/

#include "socketlpx.h"

#define LPXTCP_DEVICE		SOCKETLPX_DEVICE_NAME
#define LPXUDP_DEVICE		SOCKETLPX_DEVICE_NAME
#define LPXTCP_DOSDEVICE	SOCKETLPX_DOSDEVICE_NAME
#define LPXUDP_DOSDEVICE	SOCKETLPX_DOSDEVICE_NAME


