//
// Do not edit this file from the Visual Studio Resource Editor
//
#ifndef APSTUDIO_INVOKED
#include <windows.h>
#include "ndasmgmt_appiniterr.h"

#pragma code_page(949)
LANGUAGE LANG_KOREAN, SUBLANG_KOREAN
STRINGTABLE
BEGIN
	IDS_APP_INIT_ERROR_TITLE				"응용 프로그램 초기화 오류"
	IDS_APP_INIT_ERROR_ADMIN_PRIV_REQUIRED	"이 프로그램을 사용하기 위해서는 관리자 권한이 필요합니다.\r\n관리자 그룹에 속한 사용자로 로그온 하여 프로그램을 실행하시기 바랍니다."
END

#endif // APSTUDIO_INVOKED
