<?xml version="1.0" encoding="utf-8" ?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="text" encoding="unicode"/>
<!-- Override built-in template -->
<xsl:param name="lang">ENU</xsl:param>
<xsl:param name="module"></xsl:param>
<xsl:param name="type">header</xsl:param>

<xsl:template match="text()"/>
<xsl:template match="/"
>;/////////////////////////////////////////////////////////////////////////
;//
;// Copyright (C) 2004 XIMETA, Inc.
;// All rights reserved.
;//
;// Module Name:
;//
;//    _ndasmsg.h
;//
;// Abstract:
;//
;//    Messages for Event Logging for the service
;//
;//
;//Notes:
;//
;//	   DO NOT EDIT THIS FILE BY HAND!
;//
;//    This file is GENERATED by the xml file.
;//    and consequently by MC tool from the _ndasmsg.mc file.
;//
;//////////////////////////////////////////////////////////////////////////
;
;
;#ifndef __NDASMSG_H_
;#define __NDASMSG_H_
;
	
MessageIdTypeDef=DWORD

SeverityNames=(
Success=0x0:STATUS_SEVERITY_SUCCESS
Informational=0x1:STATUS_SEVERITY_INFORMATIONAL
Warning=0x2:STATUS_SEVERITY_WARNING
Error=0x3:STATUS_SEVERITY_ERROR
)

FacilityNames=(
LANSCSIHelperService=0xE01
NDASSVC=0x002
NDASUSER=0x001
NDASDM=0xF10
)

LanguageNames=(
NEU=0000:_ndasmsg000
ENU=0x409:_ndasmsg409
KOR=0x412:_ndasmsg412
GER=0x407:_ndasmsg407
)

<xsl:apply-templates/>

;#endif /* __NDASMSG_H_ */
</xsl:template>

<xsl:template match="messages">
	<!-- <xsl:if test="@module=$module and @langid=$lang" > -->
		<xsl:apply-templates select="message"/>
	<!-- </xsl:if> -->
</xsl:template>

<!--

- Sample XML data

<message
	id="0xFFFF" 
	symbolicName="NDAS_MSG_ERR_UNKNOWN" 
	severity="Error" 
	facility="Application">
<text language="ENU">Unknown Application Error</text>
<text language="KOR">알 수 없는 오류</text>
</message>

- Sample Output

MessageId=0xFFFF SymbolicName=NDAS_MSG_ERR_UNKNOWN
Severity=Error
Facility=Application
Language=ENU
Unknown Application Error
.
Language=KOR
알 수 없는 오류
.

-->
<xsl:template match="message">
MessageId=<xsl:value-of select="@id" />
SymbolicName=<xsl:value-of select="@symbolicName" />
Severity=<xsl:value-of select="@severity" />
Facility=<xsl:value-of select="@facility" />
<xsl:for-each select="text">
Language=<xsl:value-of select="@lang" />
<!-- xsl:text is required for CR (Carridge Return) -->
<xsl:text>
</xsl:text>
<xsl:value-of select="text()"/>
.
</xsl:for-each>
</xsl:template>

<!--
<xsl:template match="$lang">
Language=<xsl:value-of select="." />
<xsl:text>
</xsl:text>
<xsl:value-of select="text()" />
.
</xsl:template>
-->

</xsl:stylesheet>