//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ndasbind.rc
//
#ifdef IDC_STATIC
#undef IDC_STATIC
#endif
#define IDC_STATIC      (-1)

#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDC_APPVER                      201
#define IDC_COMPVER                     202
#define IDC_LINK                        203
#define IDC_APPNAME                     204
#define IDI_NDAGGR_BROKEN               206
#define IDI_NDAGGR_OK                   207
#define IDI_ND_SLAVE                    210
#define IDI_ND_BADKEY                   211
#define IDI_ND_DISABLED                 212
#define IDI_ND_INUSE                    213
#define IDI_ND_NOEXIST                  214
#define IDI_ND_RO                       215
#define IDI_ND_RW                       216
#define IDB_ABOUT_HEADER                216
#define IDI_NDMIRR_OK                   219
#define IDI_NDMIRR_BROKEN               222
#define IDR_CONTEXT_MENU                223
#define IDD_UNBIND                      225
#define IDD_SYNC                        227
#define IDB_MAINFRAME                   228
#define IDR_MIRROR_MENU                 230
#define IDD_BIND_PAGE1                  234
#define IDD_BIND_PAGE2                  235
#define IDD_ADDMIRROR_SYNC              236
#define IDD_SELSOURCE                   237
#define IDD_PROPERTY_PAGE1              238
#define IDD_PROPERTY_PAGE2              239
#define IDD_ADDMIR                      240
#define IDD_PROPERTY_PAGE3              241
#define IDD_UNBIND1                     242
#define IDD_UNBIND_MIRROR               242
#define IDB_DRAG                        244
#define IDD_RECOVER                     249
#define IDS_MAINFRAME_SERVICE_FAIL_AT_START 251
#define IDS_MAINFRAME_NO_DISK_TO_MIRROR 254
#define IDS_MAINFRAME_OLD_VERSION       255
#define IDS_MAINFRAME_SERVICE_FAIL      256
#define IDS_DISKPROPERTYPAGE_MIGRATE_DISK_NOT_EXIST 279
#define IDS_DISKPROPERTYPAGE_MIGRATE_CONFIRM 280
#define IDS_DISKPROPERTYPAGE_MIGRATE_FAIL 282
#define IDS_DISKPROPERTYPAGE_MIGRATE_SUCCESS 283
#define IDS_DISKPROPERTYPAGE_WRITEKEY_PRESENT 284
#define IDS_DISKPROPERTYPAGE_WRITEKEY_NOT_PRESENT 285
#define IDS_DISKPROPERTYPAGE_SIZE_IN_GB 286
#define IDS_DISKPROPERTYPAGE_LIST_COL_NAME 287
#define IDS_DISKPROPERTYPAGE_LIST_COL_VALUE 288
#define IDS_SELECTMIRDLG_NO_DISK_SELECTED 289
#define IDS_SELECTMIRDLG_SMALLER_DISK   290
#define IDS_UIHANDLER_PROPERTY_NUM_BOUND_DISK 291
#define IDS_UIHANDLER_PROPERTY_NUM_BOUND_DISK_TOOLTIP 292
#define IDS_UIHANDLER_PROPERTY_DIRTY    293
#define IDS_UIHANDLER_PROPERTY_DIRTY_TRUE 294
#define IDS_UIHANDLER_PROPERTY_DIRTY_FALSE 295
#define IDS_UIHANDLER_PROPERTY_DIRTY_TOOLTIP 296
#define IDS_UIHANDLER_CLEARDIB_FAIL     297
#define IDS_UIHANDLER_CLEARDIB_SUCCESS  298
#define IDS_UIHANDLER_PROPERTY_MODEL    299
#define IDS_UIHANDLER_PROPERTY_MODEL_TOOLTIP 300
#define IDS_UIHANDLER_PROPERTY_SERIALNO 301
#define IDS_UIHANDLER_PROPERTY_SERIALNO_TOOLTIP 302
#define IDS_UIHANDLER_CLEARDIB_CONFIRM  303
#define IDS_DISKPROPERTYPAGE_GENERALTAB 307
#define IDS_DISKPROPERTYPAGE_HARDWARETAB 308
#define IDS_ABOUTDLG_PRODUCT_NAME       309
#define IDS_ABOUTDLG_PRODUCT_VER        310
#define IDS_ABOUTDLG_COL_COMPONENT      311
#define IDS_ABOUTDLG_COL_VERSION        312
#define IDS_ABOUTDLG_COMPONENT_VER      313
#define IDS_LISTVIEW_SIZE_IN_GB         314
#define IDS_LISTVIEW_COL_NAME           315
#define IDS_LISTVIEW_COL_ID             316
#define IDS_LISTVIEW_COL_SIZE           317
#define IDS_LISTVIEW_COL_EMPTY          318
#define IDS_COMMAND_BIND                319
#define IDS_COMMAND_UNBIND              320
#define IDS_COMMAND_SYNCHRONIZE         321
#define IDS_COMMAND_ADDMIRROR           323
#define IDS_COMMAND_CLEARDIB            324
#define IDS_APPLICATION                 326
#define IDS_BINDPAGE_CAPTION            327
#define IDS_DISKPROPERTYPAGE_CAPTION    329
#define IDS_BINDPAGE_FAIL_TO_BIND_DISK  330
#define IDS_COMMAND_SINGLE              335
#define IDS_WARNING_SINGLE              336
#define IDS_WARNING_SINGLE_AFTER        337
#define IDS_ERROR_TITLE                 338
#define IDS_MAINFRAME_SINGLE_ACCESS_FAIL 339
#define IDD_ERROR                       340
#define IDC_ERROR_ICON                  341
#define IDC_ERROR_DESCRIPTION           342
#define IDC_ERROR_MESSAGE               343
#define IDS_ERROR_NDAS_DESCRIPTION_FMT  345
#define IDS_ERROR_SYSTEM_DESCRIPTION_FMT 346
#define IDS_WARNING_BIND                347
#define IDS_WARNING_BIND_AFTER          348
#define IDS_ERROR_NOT_REGISTERD_WRITE_FMT 352
#define IDS_WARNING_UNBIND              357
#define IDS_WARNING_UNBIND_AFTER        358
#define IDS_BIND_FAIL_AT_SINGLE_NDAS_FMT 360
#define IDS_BIND_FAIL                   361
#define IDC_LAST_ERROR_MESSAGE          362
#define IDD_WAIT                        363
#define IDC_WAIT_MESSAGE                364
#define IDC_WAIT_ICON                   365
#define IDS_STATUS_REFRESH              366
#define IDS_DISKPROPERTYPAGE_MIGRATE_FAIL_AT_FMT 367
#define IDS_LOGDEV_TYPE                 368
#define IDS_LOGDEV_TYPE_DISK_RAID0      369
#define IDS_LOGDEV_TYPE_DISK_RAID1      370
#define IDS_LOGDEV_TYPE_DISK_RAID2      371
#define IDS_LOGDEV_TYPE_DISK_RAID3      372
#define IDS_LOGDEV_TYPE_DISK_RAID4      373
#define IDS_LOGDEV_TYPE_DISK_RAID5      374
#define IDS_LOGDEV_TYPE_AGGREGATED_DISK 375
#define IDS_LOGDEV_TYPE_CF_DRIVE        376
#define IDS_LOGDEV_TYPE_DVD_DRIVE       377
#define IDS_LOGDEV_TYPE_MIRRORED_DISK   378
#define IDS_LOGDEV_TYPE_MO_DRIVE        379
#define IDS_LOGDEV_TYPE_SINGLE_DISK     380
#define IDS_LOGDEV_TYPE_UNKNOWN_FMT     381
#define IDS_LOGDEV_TYPE_VIRTUAL_DVD_DRIVE 382
#define IDC_DEVICE_ID                   383
#define IDS_WARNING_NOT_NEED_RECOVER    384
#define IDS_WARNING_ADD_MIRROR          385
#define IDS_UNIDEV_TYPE_DISK_EMPTY      386
#define IDS_LISTVIEW_COL_STATUS         387
#define IDS_LISTVIEW_COL_TYPE           388
#define IDS_LISTVIEW_COL_FAULT          389
#define IDS_FT_UNIT                     390
#define IDS_FT_FAULT_TOLERANT           391
#define IDS_FT_NOT_FAULT_TOLERANT       392
#define IDS_FT_MISSING                  393
#define IDS_FT_DIRTY                    394
#define IDS_FT_NEED_REPAIR              395
#define IDS_STATUS_NOT_CONNECTED        396
#define IDS_STATUS_IN_USE               397
#define IDS_STATUS_READ_ONLY            398
#define IDS_STATUS_FINE                 399
#define IDM_TOOL_MIGRATE                400
#define IDS_COMMAND_MIGRATE             401
#define IDS_WARNING_UNBIND_MIR          402
#define IDS_WARNING_UNBIND_AFTER_MIR    403
#define IDM_TOOL_REPAIR                 404
#define IDS_COMMAND_REPAIR              405
#define IDD_REPAIR                      406
#define IDS_MAINFRAME_NO_DISK_REPAIR    407
#define IDS_MAINFRAME_NOT_READY_REPAIR  408
#define IDS_REPAIR_FAIL                 409
#define IDS_RECOVERDLG_TASK_REPAIR      410
#define IDD_BIND_WIZARD_INTRO           411
#define IDC_BIG_BOLD_TITLE              412
#define IDD_BIND_WIZARD_TYPE            413
#define IDC_BIND_TYPE_DESCRIPTION       414
#define IDD_BIND_WIZARD_SELECT_DISK     415
#define IDC_BTN_REMOVE_ALL              416
#define IDC_BIND_WIZ_AVAILABLE          417
#define IDC_BIND_WIZ_SELECTED           418
#define IDC_BIND_WIZ_SIZE               419
#define IDD_BIND_WIZARD_COMPLETE        420
#define IDC_EDIT_BIND_SETTING           421
#define IDS_BNZ_TITLE                   422
#define IDS_BNZ_BIND_TYPE_HEADER_TITLE  423
#define IDS_BNZ_BIND_TYPE_HEADER_SUBTITLE 424
#define IDS_BNZ_SELECT_DISK_HEADER_TITLE 425
#define IDS_BNZ_SELECT_DISK_HEADER_SUBTITLE 426
#define IDB_WATERMARK256                427
#define IDB_BANNER256                   428
#define IDS_BIG_BOLD_FONT_NAME          429
#define IDS_BIG_BOLD_FONT_SIZE          430
#define IDC_BIND_WIZ_COUNT              431
#define IDC_BIND_RESULT                 432
#define IDS_BNZ_COMPLETE_SUCCESS        433
#define IDS_BNZ_COMPLETE_FAIL           434
#define IDS_BNZ_COMPLETE_RESULT_TYPE_FMT 435
#define IDS_BNZ_COMPLETE_RESULT_DISKS   436
#define IDS_BNZ_COMPLETE_RESULT_SIZE_FMT 437
#define IDS_BNZ_COMPLETE_RESULT_FAILED_ON_FMT 438
#define IDS_BNZ_DESC_AGGREGATION        439
#define IDS_BNZ_DESC_RAID0              440
#define IDS_BNZ_DESC_RAID1              441
#define IDS_BNZ_DESC_RAID4              442
#define IDC_MAINDLG_AGGR_BINDBTN        1000
#define IDC_MAINDLG_MIRR_BINDBTN        1001
#define IDC_MAINDLG_AGGR_UNBINDBTN      1002
#define IDC_MAINDLG_RELOAD              1003
#define IDC_TREE_NETDISK                1004
#define IDC_LIST_SINGLE                 1010
#define IDC_LIST_MIRROR                 1011
#define IDC_LIST_PRIMARY                1012
#define IDC_CHK_MIRROR                  1013
#define IDC_BTN_TO_PRIMARY              1014
#define IDC_BTN_FROM_PRIMARY            1015
#define IDC_BTN_TO_MIRROR               1016
#define IDC_BTN_FROM_MIRROR             1017
#define IDC_LIST_UNBIND                 1020
#define IDC_TEXT_ELAPSEDTIME            1021
#define IDC_TEXT_LEFTTIME               1022
#define IDC_TEXT_RATE                   1023
#define IDC_PROGBAR_JOB                 1024
#define IDC_PROGBAR                     1024
#define IDC_TEXT_SOURCE                 1028
#define IDC_TEXT_DEST                   1029
#define IDC_TEXT_PHASE                  1030
#define IDC_PRODUCTVER                  1031
#define IDC_TEXT_PRODUCTVER             1031
#define IDC_FILEVER                     1032
#define IDC_TEXT_FILEVER                1032
#define IDC_ABOUTBOX_HYPERLINK          1033
#define IDI_COMPANY                     1034
#define IDC_TEXT_COPYWRITE              1035
#define IDC_EDIT_DISKCOUNT              1051
#define IDC_BTN_ADD                     1052
#define IDC_BTN_REMOVE                  1053
#define IDC_LIST_BIND                   1054
#define IDC_TYPE                        1055
#define IDC_BTN_UP                      1055
#define IDC_TYPE2                       1056
#define IDC_BTN_DOWN                    1056
#define IDC_EDIT2                       1057
#define IDC_BIND_TYPE_AGGR              1057
#define IDC_EDIT3                       1058
#define IDC_BUTTON1                     1059
#define IDC_BTN_MIGRATE                 1059
#define IDC_BUTTON2                     1060
#define IDC_DISKLIST                    1062
#define IDC_EDIT_NAME                   1063
#define IDC_LIST_PROPERTY               1064
#define IDC_COPYWRITE                   1065
#define IDC_EDIT_ID                     1066
#define IDC_IMAGE                       1066
#define IDC_EDIT_WRITEKEY               1067
#define IDC_TREE1                       1067
#define IDC_EDIT_CAPACITY               1068
#define IDC_ST_MIGRATE                  1069
#define IDC_TEXT_MIGRATE                1070
#define IDC_BIND_TYPE_RAID0             1071
#define IDC_BIND_TYPE_RAID1             1072
#define IDC_BIND_TYPE_RAID4             1073
#define IDC_TEXT_BIND_TYPE              1074
#define IDS_RECOVER_BTN_CANCEL          1075
#define IDS_RECOVER_BTN_CLOSE           1076
#define IDC_COMBO_DISKCOUNT             1077
#define IDS_RECOVERDLG_PHASE_READY      1078
#define IDS_RECOVERDLG_PHASE_SYNC       1079
#define IDS_RECOVERDLG_PHASE_DONE       1080
#define IDS_RECOVERDLG_FAIL             1081
#define IDS_RECOVERDLG_TASK_ADD_MIRROR  1082
#define IDS_RECOVERDLG_TASK_RECOVER     1083
#define IDS_FAIL_TO_ACCESS_EXCLUSIVELY  1084
#define IDM_TOOL_SPAREADD               1085
#define IDM_TOOL_SPAREREMOVE            1086
#define IDM_EXIT                        32773
#define IDM_TOOL_BIND                   32774
#define IDM_TOOL_UNBIND                 32776
#define IDM_TOOL_SINGLE                 32777
#define IDM_TOOL_SYNCHRONIZE            32779
#define IDM_TOOL_MIRROR                 32781
#define IDM_HELP_ABOUT                  32782
#define IDM_TOOL_CLEARDIB               32783
#define IDM_TOOL_ADDMIRROR              32791
#define IDM_TOOL_REFRESH                32792
#define IDM_TOOL_PROPERTY               32793
#define IDM_REFRESH_STATUS              32794
#define ID_CONTEXT                      32795
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define IDS_COMMAND_SPAREADD            57665
#define IDS_FT_FAULT                    1087
#define IDS_FT_IN_SYNC                  1088
#define IDS_FT_FAULT_CHILD              1089
#define IDS_FT_FAULT_SPARE              1090
#define IDD_DEVICE_LIST                 1091
#define IDC_LIST_DEVICE                 1092
#define IDS_SPARE_ADD_DLG_CAPTION       1093
#define IDS_SPARE_ADD_DLG_MESSAGE       1094
#define IDC_STATIC_MESSAGE              1095
#define IDS_SPARE_ADD_DLG_SIZE_FAIL     1096
#define IDS_MIRROR_ADD_DLG_CAPTION      1097
#define IDS_MIRROR_ADD_DLG_MESSAGE      1098
#define IDS_UNBIND_DLG_CAPTION          1099
#define IDS_UNBIND_DLG_MESSAGE          1100
#define IDM_TOOL_REPLACE_DEVICE         1101
#define IDM_TOOL_REPLACE_UNIT_DEVICE    1102
#define IDS_OPERATION_FAIL              1103
#define IDS_SPARE_REMOVE_DLG_CAPTION    1104
#define IDS_SPARE_REMOVE_DLG_MESSAGE    1105
#define IDS_SINGLE_DLG_CAPTION          1106
#define IDS_SINGLE_DLG_MESSAGE          1107
#define IDI_BASIC                       1108
#define IDI_AGGR                        1109
#define IDI_RAID0                       1110
#define IDI_RAID1                       1111
#define IDI_RAID4                       1112
#define IDI_DVD                         1113
#define IDI_VDVD                        1114
#define IDI_FLASH                       1115
#define IDI_MO                          1116
#define IDI_FAIL                        1117


// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        325
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
